'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'gu' | 'mr' | 'bn' | 'kn'

export interface LanguageOption {
  code: Language
  label: string
  nativeName: string
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeName: 'English' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'gu', label: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr', label: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা' },
  { code: 'kn', label: 'Kannada', nativeName: 'ಕನ್ನಡ' },
]

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    brandName: 'CardioSense AI',
    dashboard: 'Dashboard',
    newAnalysis: 'New Analysis',
    history: 'History',
    doctorPortal: 'Doctor Portal',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    welcomeBack: 'Welcome back',
    patientMode: 'Patient Mode',
    doctorMode: 'Doctor Mode',
    adminMode: 'Admin Mode',
    uploadNewSignal: 'Upload New Signal',
    historyTrends: 'History & Trends',
    screeningReports: 'Screening Reports',
    signalType: 'Select Signal Type',
    chooseFile: 'Choose Signal File',
    analyzeNow: 'Analyze Recording Now',
    signalQuality: 'Signal Quality Score',
    heartRate: 'Heart Rate Analysis',
    aiPrediction: 'AI Model Prediction',
    downloadPdf: 'Download PDF Report',
    dateAndTime: 'Date & Time',
    filterType: 'Filter Type',
    sortBy: 'Sort By',
    recentAnalyses: 'Recent Analysis Sessions',
    hospitalMode: 'Hospital Mode',
    cardiacScreeningUpload: 'Cardiac Screening & Patient Upload',
    doctorClinicalUpload: 'Doctor Clinical Upload & Patient Intake',
    uploadSubtitle: 'Upload a single or multi-lead cardiac recording or select a pre-loaded research dataset. Attach patient details to save directly into history & doctor patient records.',
    voltage: 'Voltage',
    ecgDesc: 'Electrocardiogram electrical signal leads.',
    optical: 'Optical',
    ppgDesc: 'Photoplethysmogram blood pulse waves.',
    instantTestDatasets: 'Instant Test Datasets',
    preloadedRecordings: 'Pre-loaded research ECG/PPG recordings',
    noFilesHint: 'No local ECG/PPG files on your device? Click any pre-loaded dataset below to test the platform instantly:',
    testDatasetsDownload: 'Test Datasets & PhysioNet WFDB Files:',
    clickToDownload: 'Click to download to PC',
    enterPatientDetails: 'Enter Patient Details & Analyze Recording',
    standardOverview: 'Standard Overview',
    hospitalDeviceLink: 'Hospital Device Link (Web Serial / Oscilloscope)',
    clinicalTrialExporter: 'Clinical Trial Exporter',
    dragDropText: 'Drag & Drop ECG or PPG Recording',
    orClickBrowse: 'or click to browse from your computer',
    supportedFormats: 'Supported: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR (PhysioNet WFDB)',
  },
  hi: {
    brandName: 'कार्डियोसेंस एआई',
    dashboard: 'डैशबोर्ड',
    newAnalysis: 'नया विश्लेषण',
    history: 'इतिहास',
    doctorPortal: 'डॉक्टर पोर्टल',
    adminPanel: 'एडमिन पैनल',
    logout: 'लॉगआउट',
    welcomeBack: 'नमस्ते, स्वागत है',
    patientMode: 'मरीज़ मोड',
    doctorMode: 'डॉक्टर मोड',
    adminMode: 'एडमिन मोड',
    uploadNewSignal: 'नया सिग्नल अपलोड करें',
    historyTrends: 'इतिहास और रुझान',
    screeningReports: 'स्क्रीनिंग रिपोर्ट',
    signalType: 'सिग्नल प्रकार चुनें',
    chooseFile: 'सिग्नल फ़ाइल चुनें',
    analyzeNow: 'अब विश्लेषण करें',
    signalQuality: 'सिग्नल गुणवत्ता स्कोर',
    heartRate: 'हृदय गति विश्लेषण',
    aiPrediction: 'एआई मॉडल भविष्यवाणी',
    downloadPdf: 'पीडीएफ रिपोर्ट डाउनलोड करें',
    dateAndTime: 'दिनांक और समय',
    filterType: 'फ़िल्टर प्रकार',
    sortBy: 'क्रमबद्ध करें',
    recentAnalyses: 'हाल के विश्लेषण सत्र',
    hospitalMode: 'अस्पताल मोड',
    cardiacScreeningUpload: 'हृदय स्क्रीनिंग एवं मरीज अपलोड',
    doctorClinicalUpload: 'डॉक्टर क्लिनिकल अपलोड एवं मरीज प्रविष्टि',
    uploadSubtitle: 'एकल या मल्टी-लीड कार्डिएक रिकॉर्डिंग अपलोड करें या प्री-लोड किए गए शोध डेटासेट का चयन करें। इतिहास और डॉक्टर मरीज रिकॉर्ड में सहेजने के लिए विवरण संलग्न करें।',
    voltage: 'वोल्टेज',
    ecgDesc: 'इलेक्ट्रोकार्डियोग्राम विद्युत सिग्नल लीड्स।',
    optical: 'ऑप्टिकल',
    ppgDesc: 'फोटोप्लेथिस्मोग्राम रक्त पल्स तरंगें।',
    instantTestDatasets: 'त्वरित परीक्षण डेटासेट',
    preloadedRecordings: 'प्री-लोड किए गए शोध ईसीजी/पीपीजी रिकॉर्डिंग',
    noFilesHint: 'क्या आपके डिवाइस पर ईसीजी/पीपीजी फ़ाइलें नहीं हैं? मंच का तुरंत परीक्षण करने के लिए नीचे किसी भी डेटासेट पर क्लिक करें:',
    testDatasetsDownload: 'परीक्षण डेटासेट एवं फिजियोनेट WFDB फ़ाइलें:',
    clickToDownload: 'पीसी पर डाउनलोड करने के लिए क्लिक करें',
    enterPatientDetails: 'मरीज का विवरण दर्ज करें और रिकॉर्डिंग का विश्लेषण करें',
    standardOverview: 'मानक अवलोकन',
    hospitalDeviceLink: 'अस्पताल उपकरण लिंक (वेब सीरियल / ऑसिस्कोप)',
    clinicalTrialExporter: 'क्लिनिकल ट्रायल निर्यातक',
    dragDropText: 'ईसीजी या पीपीजी रिकॉर्डिंग ड्रैग और ड्रॉप करें',
    orClickBrowse: 'या अपने कंप्यूटर से ब्राउज़ करने के लिए क्लिक करें',
    supportedFormats: 'समर्थित: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR (फिजियोनेट WFDB)',
  },
  ta: {
    brandName: 'கார்டியோசென்ஸ் AI',
    dashboard: 'டாஷ்போர்டு',
    newAnalysis: 'புதிய பகுப்பாய்வு',
    history: 'வரலாறு',
    doctorPortal: 'மருத்துவர் தளம்',
    adminPanel: 'நிர்வாகக் குழு',
    logout: 'வெளியேறு',
    welcomeBack: 'நல்வரவு',
    patientMode: 'நோயாளி பயன்முறை',
    doctorMode: 'மருத்துவர் பயன்முறை',
    adminMode: 'நிர்வாகி பயன்முறை',
    uploadNewSignal: 'புதிய சமிக்ஞையைப் பதிவேற்று',
    historyTrends: 'வரலாறு மற்றும் போக்குகள்',
    screeningReports: 'பரிசோதனை அறிக்கைகள்',
    signalType: 'சமிக்ஞை வகையைத் தேர்ந்தெடு',
    chooseFile: 'கோப்பைத் தேர்ந்தெடு',
    analyzeNow: 'இப்போது பகுப்பாய்வு செய்',
    signalQuality: 'சமிக்ஞை தர மதிப்பீடு',
    heartRate: 'இதய துடிப்பு பகுப்பாய்வு',
    aiPrediction: 'AI கணிப்பு',
    downloadPdf: 'PDF அறிக்கையைப் பதிவிறக்கு',
    dateAndTime: 'தேதி மற்றும் நேரம்',
    filterType: 'வடிகட்டி வகை',
    sortBy: 'வரிசைப்படுத்து',
    recentAnalyses: 'சமீபத்திய பகுப்பாய்வுகள்',
    hospitalMode: 'மருத்துவமனை முறை',
    cardiacScreeningUpload: 'இதய பரிசோதனை & நோயாளி பதிவேற்றம்',
    doctorClinicalUpload: 'மருத்துவர் மருத்துவ பதிவேற்றம்',
    uploadSubtitle: 'கார்டியாக் பதிவை பதிவேற்றவும் அல்லது ஆராய்ச்சி தரவுத்தொகுப்பைத் தேர்ந்தெடுக்கவும்.',
    voltage: 'மின்னழுத்தம்',
    ecgDesc: 'எலக்ட்ரோ கார்டியோகிராம் மின்சார சமிக்ஞைகள்.',
    optical: 'ஒளியியல்',
    ppgDesc: 'ஃபோட்டோபிளெதிஸ்மோகிராம் இரத்த துடிப்பு அலைகள்.',
    instantTestDatasets: 'உடனடி சோதனை தரவுத்தொகுப்புகள்',
    preloadedRecordings: 'முன்பே ஏற்றப்பட்ட ஆராய்ச்சி பதிவுகள்',
    noFilesHint: 'கோப்புகள் இல்லையா? உடனடியாக சோதிக்க கீழே உள்ள தரவுத்தொகுப்பைக் கிளிக் செய்யவும்:',
    testDatasetsDownload: 'சோதனை தரவுத்தொகுப்புகள் & WFDB கோப்புகள்:',
    clickToDownload: 'கணினியில் பதிவிறக்க கிளிக் செய்யவும்',
    enterPatientDetails: 'நோயாளி விவரங்களை உள்ளிட்டு பகுப்பாய்வு செய்யவும்',
    standardOverview: 'தரமான பார்வை',
    hospitalDeviceLink: 'மருத்துவமனை சாதன இணைப்பு',
    clinicalTrialExporter: 'மருத்துவ சோதனை ஏற்றுமதியாளர்',
    dragDropText: 'ECG அல்லது PPG பதிவை இழுத்து விடவும்',
    orClickBrowse: 'அல்லது கணினியிலிருந்து தேர்ந்தெடுக்க கிளிக் செய்யவும்',
    supportedFormats: 'ஆதரிக்கப்படும் வடிவங்கள்: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
  },
  te: {
    brandName: 'కార్డియోసెన్స్ AI',
    dashboard: 'డాష్‌బోర్డ్',
    newAnalysis: 'కొత్త విశ్లేషణ',
    history: 'చరిత్ర',
    doctorPortal: 'వైద్యుల పోర్టల్',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    logout: 'లాగ్‌అవుట్',
    welcomeBack: 'స్వాగతం',
    patientMode: 'పేషెంట్ మోడ్',
    doctorMode: 'డాక్టర్ మోడ్',
    adminMode: 'అడ్మిన్ మోడ్',
    uploadNewSignal: 'కొత్త సిగ్నల్ అప్‌లోడ్ చేయండి',
    historyTrends: 'చరిత్ర మరియు ట్రెండ్‌లు',
    screeningReports: 'స్క్రీనింగ్ రిపోర్టులు',
    signalType: 'సిగ్నల్ రకాన్ని ఎంచుకోండి',
    chooseFile: 'ఫైల్‌ను ఎంచుకోండి',
    analyzeNow: 'ఇప్పుడే విశ్లేషించండి',
    signalQuality: 'సిగ్నల్ క్వాలిటీ స్కోర్',
    heartRate: 'గుండె వేగం విశ్లేషణ',
    aiPrediction: 'AI అంచనా',
    downloadPdf: 'PDF నివేదికను డౌన్‌లోడ్ చేయండి',
    dateAndTime: 'తేదీ మరియు సమయం',
    filterType: 'ఫిల్టర్ రకం',
    sortBy: 'క్రమబద్ధీకరించు',
    recentAnalyses: 'ఇటీవలి విశ్లేషణలు',
    hospitalMode: 'హాస్పిటల్ మోడ్',
    cardiacScreeningUpload: 'కార్డియాక్ స్క్రీనింగ్ & పేషెంట్ అప్‌లోడ్',
    doctorClinicalUpload: 'డాక్టర్ క్లినికల్ అప్‌లోడ్',
    uploadSubtitle: 'కార్డియాక్ రికార్డింగ్‌ను అప్‌లోడ్ చేయండి లేదా రీసెర్చ్ డేటాసెట్‌ను ఎంచుకోండి.',
    voltage: 'వోల్టేజ్',
    ecgDesc: 'ఎలక్ట్రోకార్డియోగామ్ ఎలక్ట్రికల్ సిగ్నల్స్.',
    optical: 'ఆప్టికల్',
    ppgDesc: 'ఫోటోప్లెథిస్మోగ్రామ్ రక్త పల్స్ తరంగాలు.',
    instantTestDatasets: 'తక్షణ పరీక్ష డేటాసెట్‌లు',
    preloadedRecordings: 'ముందుగా లోడ్ చేసిన పరిశోధన రికార్డింగ్‌లు',
    noFilesHint: 'ఫైల్‌లు లేవా? ప్లాట్‌ఫారమ్‌ను పరీక్షించడానికి కింద క్లిక్ చేయండి:',
    testDatasetsDownload: 'పరీక్ష డేటాసెట్‌లు & WFDB ఫైల్‌లు:',
    clickToDownload: 'PC లోకి డౌన్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    enterPatientDetails: 'పేషెంట్ వివరాలను నమోదు చేసి విశ్లేషించండి',
    standardOverview: 'స్టాండర్డ్ ఓవర్‌వ్యూ',
    hospitalDeviceLink: 'హాస్పిటల్ పరికర లింక్',
    clinicalTrialExporter: 'క్లినికల్ ట్రయల్ ఎక్స్‌పోర్టర్',
    dragDropText: 'ECG లేదా PPG రికార్డింగ్‌ను డ్రాగ్ & డ్రాప్ చేయండి',
    orClickBrowse: 'లేదా కంప్యూటర్ నుండి బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    supportedFormats: 'మద్దతు ఉన్న రకాలు: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
  },
  gu: {
    brandName: 'કાર્ડિઓસેન્સ AI',
    dashboard: 'ડેશબોર્ડ',
    newAnalysis: 'નવું વિશ્લેષણ',
    history: 'ઇતિહાસ',
    doctorPortal: 'ડૉક્ટર પોર્ટલ',
    adminPanel: 'એડમિન પેનલ',
    logout: 'લૉગઆઉટ',
    welcomeBack: 'સ્વાગત છે',
    patientMode: 'દર્દી મોડ',
    doctorMode: 'ડૉક્ટર મોડ',
    adminMode: 'એડમિન મોડ',
    uploadNewSignal: 'નવો સિગ્નલ અપલોડ કરો',
    historyTrends: 'ઇતિહાસ અને પ્રવાહો',
    screeningReports: 'સ્ક્રીનીંગ રિપોર્ટ્સ',
    signalType: 'સિગ્નલ પ્રકાર પસંદ કરો',
    chooseFile: 'સિગ્નલ ફાઇલ પસંદ કરો',
    analyzeNow: 'હવે વિશ્લેષણ કરો',
    signalQuality: 'સિગ્નલ ગુણવત્તા સ્કોર',
    heartRate: 'હૃદયના ધબકારાનું વિશ્લેષણ',
    aiPrediction: 'AI મોડેલ આગાહી',
    downloadPdf: 'PDF રિપોર્ટ ડાઉનલોડ કરો',
    dateAndTime: 'તારીખ અને સમય',
    filterType: 'ફિલ્ટર પ્રકાર',
    sortBy: 'ક્રમમાં ગોઠવો',
    recentAnalyses: 'તાજેતરના વિશ્લેષણ',
    hospitalMode: 'હોસ્પિટલ મોડ',
    cardiacScreeningUpload: 'હૃદય સ્ક્રીનીંગ અને દર્દી અપલોડ',
    doctorClinicalUpload: 'ડૉક્ટર ક્લિનિકલ અપલોડ',
    uploadSubtitle: 'કાર્ડિયાક રેકોર્ડિંગ અપલોડ કરો અથવા રિસર્ચ ડેટાસેટ પસંદ કરો.',
    voltage: 'વોલ્ટેજ',
    ecgDesc: 'ઇલેક્ટ્રોકાર્ડિયોગ્રામ સિગ્નલ લાઇન.',
    optical: 'ઓપ્ટિકલ',
    ppgDesc: 'ફોટોપ્લેથિસ્મોગ્રામ પલ્સ વેવ્સ.',
    instantTestDatasets: 'ઝડપી પરીક્ષણ ડેટાસેટ્સ',
    preloadedRecordings: 'પ્રી-લોડેડ સંશોધન રેકોર્ડિંગ્સ',
    noFilesHint: 'ફાઇલો નથી? પ્લેટફોર્મ ચકાસવા માટે નીચે કિલક કરો:',
    testDatasetsDownload: 'ટેસ્ટ ડેટાસેટ્સ અને WFDB ફાઇલો:',
    clickToDownload: 'પીસી પર ડાઉનલોડ કરવા ક્લિક કરો',
    enterPatientDetails: 'દર્દીની વિગતો દાખલ કરો અને વિશ્લેષણ કરો',
    standardOverview: 'સામાન્ય વિહંગાવલોકન',
    hospitalDeviceLink: 'હોસ્પિટલ ડિવાઇસ લિંક',
    clinicalTrialExporter: 'ક્લિનિકલ ટ્રાયલ એક્સપોર્ટર',
    dragDropText: 'ECG અથવા PPG રેકોર્ડિંગ ડ્રેગ અને ડ્રોપ કરો',
    orClickBrowse: 'અથવા તમારા કમ્પ્યુટરથી બ્રાઉઝ કરવા માટે કિલક કરો',
    supportedFormats: 'સપોર્ટેડ: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
  },
  mr: {
    brandName: 'कार्डिओसेन्स AI',
    dashboard: 'डॅशबोर्ड',
    newAnalysis: 'नवीन विश्लेषण',
    history: 'इतिहास',
    doctorPortal: 'डॉक्टर पोर्टल',
    adminPanel: 'ॲडमिन पॅनेल',
    logout: 'लॉगआउट',
    welcomeBack: 'सुस्वागतम',
    patientMode: 'रुग्ण मोड',
    doctorMode: 'डॉक्टर मोड',
    adminMode: 'ॲडमिन मोड',
    uploadNewSignal: 'नवीन सिग्नल अपलोड करा',
    historyTrends: 'इतिहास आणि ट्रेंड',
    screeningReports: 'स्क्रीनिंग अहवाल',
    signalType: 'सिग्नल प्रकार निवडा',
    chooseFile: 'सिग्नल फाइल निवडा',
    analyzeNow: 'आता विश्लेषण करा',
    signalQuality: 'सिग्नल गुणवत्ता स्कोर',
    heartRate: 'हृदयगती विश्लेषण',
    aiPrediction: 'AI मॉडेल भाकीत',
    downloadPdf: 'PDF अहवाल डाउनलोड करा',
    dateAndTime: 'दिनांक आणि वेळ',
    filterType: 'फिल्टर प्रकार',
    sortBy: 'क्रमवारी लावा',
    recentAnalyses: 'नुकतेच केलेले विश्लेषण',
    hospitalMode: 'हॉस्पिटल मोड',
    cardiacScreeningUpload: 'हृदय तपासणी आणि रुग्ण अपलोड',
    doctorClinicalUpload: 'डॉक्टर क्लिनिकल अपलोड',
    uploadSubtitle: 'कार्डियाक रेकॉर्डिंग अपलोड करा किंवा संशोधन डेटासेट निवडा.',
    voltage: 'व्होल्टेज',
    ecgDesc: 'इलेक्ट्रोकार्डिओग्राम इलेक्ट्रिकल सिग्नल.',
    optical: 'ऑप्टिकल',
    ppgDesc: 'फोटोप्लेथिस्मोग्राम रक्त लहरी.',
    instantTestDatasets: 'झटपट चाचणी डेटासेट',
    preloadedRecordings: 'प्री-लोड केलेले संशोधन रेकॉर्डिंग',
    noFilesHint: 'फायली नाहीत? प्लॅटफॉर्म तपासण्यासाठी खाली क्लिक करा:',
    testDatasetsDownload: 'चाचणी डेटासेट आणि WFDB फायली:',
    clickToDownload: 'पीसी वर डाउनलोड करण्यासाठी क्लिक करा',
    enterPatientDetails: 'रुग्णाची माहिती भरा आणि विश्लेषण करा',
    standardOverview: 'मानक विहंगावलोकन',
    hospitalDeviceLink: 'हॉस्पिटल डिव्हाइस लिंक',
    clinicalTrialExporter: 'क्लिनिकल ट्रायल एक्सपोर्टर',
    dragDropText: 'ECG किंवा PPG रेकॉर्डिंग ड्रॅग आणि ड्रॉप करा',
    orClickBrowse: 'किंवा संगणकावरून निवडण्यासाठी क्लिक करा',
    supportedFormats: 'समर्थित: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
  },
  bn: {
    brandName: 'কার্ডিওসেন্স AI',
    dashboard: 'ড্যাশবোর্ড',
    newAnalysis: 'নতুন বিশ্লেষণ',
    history: 'ইতিহাস',
    doctorPortal: 'ডাক্তার পোর্টাল',
    adminPanel: 'অ্যাডমিন প্যানেল',
    logout: 'লগআউট',
    welcomeBack: 'স্বাগতম',
    patientMode: 'রোগী মোড',
    doctorMode: 'ডাক্তার মোড',
    adminMode: 'অ্যাডমিন মোড',
    uploadNewSignal: 'নতুন সংকেত আপলোড করুন',
    historyTrends: 'ইতিহাস এবং প্রবণতা',
    screeningReports: 'স্ক্রিনিং রিপোর্ট',
    signalType: 'সংকেত প্রকার নির্বাচন করুন',
    chooseFile: 'সংকেত ফাইল নির্বাচন করুন',
    analyzeNow: 'এখন বিশ্লেষণ করুন',
    signalQuality: 'সংকেত গুণমান স্কোর',
    heartRate: 'হৃদস্পন্দন বিশ্লেষণ',
    aiPrediction: 'AI মডেল পূর্বাভাস',
    downloadPdf: 'পিডিএফ রিপোর্ট ডাউনলোড করুন',
    dateAndTime: 'তারিখ ও সময়',
    filterType: 'ফিল্টার প্রকার',
    sortBy: 'সাজান',
    recentAnalyses: 'সাম্প্রতিক বিশ্লেষণ',
    hospitalMode: 'হাসপাতাল মোড',
    cardiacScreeningUpload: 'হৃদরোগ স্ক্রিনিং এবং রোগী আপলোড',
    doctorClinicalUpload: 'ডাক্তার ক্লিনিকাল আপলোড',
    uploadSubtitle: 'কার্ডিয়াক রেকর্ডিং আপলোড করুন অথবা গবেষণা ডেটাসেট নির্বাচন করুন।',
    voltage: 'ভোল্টেজ',
    ecgDesc: 'ইলেক্ট্রোকার্ডিওগ্রাম বৈদ্যুতিক সংকেত।',
    optical: 'অপটিক্যাল',
    ppgDesc: 'ফোটোপ্লেথিসমোগ্রাম রক্ত স্পন্দন তরঙ্গ।',
    instantTestDatasets: 'তাত্ক্ষণিক পরীক্ষা ডেটাসেট',
    preloadedRecordings: 'প্রি-লোড করা গবেষণা রেকর্ডিং',
    noFilesHint: 'ফাইল নেই? অবিলম্বে পরীক্ষা করতে নিচে ক্লিক করুন:',
    testDatasetsDownload: 'পরীক্ষা ডেটাসেট এবং WFDB ফাইল:',
    clickToDownload: 'পিসিতে ডাউনলোড করতে ক্লিক করুন',
    enterPatientDetails: 'রোগীর বিবরণ প্রদান করুন এবং বিশ্লেষণ করুন',
    standardOverview: 'মানক ওভারভিউ',
    hospitalDeviceLink: 'হাসপাতাল ডিভাইস লিঙ্ক',
    clinicalTrialExporter: 'ক্লিনিকাল ট্রায়াল এক্সপোর্টার',
    dragDropText: 'ECG বা PPG রেকর্ডিং ড্র্যাগ ও ড্রপ করুন',
    orClickBrowse: 'অথবা কম্পিউটার থেকে ব্রাউজ করতে ক্লিক করুন',
    supportedFormats: 'সমর্থিত: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
  },
  kn: {
    brandName: 'ಕಾರ್ಡಿಯೋಸೆನ್ಸ್ AI',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    newAnalysis: 'ಹೊಸ ವಿಶ್ಲೇಷಣೆ',
    history: 'ಇತಿಹಾಸ',
    doctorPortal: 'ವೈದ್ಯರ ಪೋರ್ಟಲ್',
    adminPanel: 'ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    welcomeBack: 'ಸ್ವಾಗತ',
    patientMode: 'ರೋಗಿ ಮೋಡ್',
    doctorMode: 'ವೈದ್ಯರ ಮೋಡ್',
    adminMode: 'ಅಡ್ಮಿನ್ ಮೋಡ್',
    uploadNewSignal: 'ಹೊಸ ಸಿಗ್ನಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    historyTrends: 'ಇತಿಹಾಸ ಮತ್ತು ಪ್ರವೃತ್ತಿಗಳು',
    screeningReports: 'ಸ್ಕ್ರೀನಿಂಗ್ ವರದಿಗಳು',
    signalType: 'ಸಿಗ್ನಲ್ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    chooseFile: 'ಸಿಗ್ನಲ್ ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    analyzeNow: 'ಈಗ ವಿಶ್ಲೇಷಿಸಿ',
    signalQuality: 'ಸಿಗ್ನಲ್ ಗುಣಮಟ್ಟದ ಸ್ಕೋರ್',
    heartRate: 'ಹೃದಯ ಬಡಿತ ವಿಶ್ಲೇಷಣೆ',
    aiPrediction: 'AI ಮಾಡೆಲ್ ಮುನ್ನೋಟ',
    downloadPdf: 'PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    dateAndTime: 'ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
    filterType: 'ಫಿಲ್ಟರ್ ಪ್ರಕಾರ',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    recentAnalyses: 'ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಗಳು',
    hospitalMode: 'ಆಸ್ಪತ್ರೆ ಮೋಡ್',
    cardiacScreeningUpload: 'ಹೃದಯ ತಪಾಸಣೆ ಮತ್ತು ರೋಗಿ ಅಪ್‌ಲೋಡ್',
    doctorClinicalUpload: 'ವೈದ್ಯಕೀಯ ಕ್ಲಿನಿಕಲ್ ಅಪ್‌ಲೋಡ್',
    uploadSubtitle: 'ಕಾರ್ಡಿಯಾಕ್ ರೆಕಾರ್ಡಿಂಗ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ లేదా ರಿಸರ್ಚ್ ಡೇಟಾಸೆಟ್ ಆಯ್ಕೆಮಾಡಿ.',
    voltage: 'ವೋಲ್ಟೇಜ್',
    ecgDesc: 'ಎಲೆಕ್ಟ್ರೋಕಾರ್ಡಿಯೋಗ್ರಾಮ್ ಸಿಗ್ನಲ್ ಲೀಡ್స్.',
    optical: 'ಆಪ್ಟಿಕಲ್',
    ppgDesc: 'ಫೋಟೋಪ್ಲೆಥಿಸ್ಮೋಗ್ರಾಮ್ ರಕ್ತದ ಬಡಿತ ಅಲೆಗಳು.',
    instantTestDatasets: 'ತ್ವರಿತ ಪರೀಕ್ಷಾ ಡೇಟಾಸೆಟ್‌ಗಳು',
    preloadedRecordings: 'ಪೂರ್ವ-ಲೋಡ್ ಮಾಡಲಾದ ರಿಸರ್ಚ್ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳು',
    noFilesHint: 'ಫೈಲ್‌ಗಳಿಲ್ಲವೇ? ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಪರೀಕ್ಷಿಸಲು ಕೆಳಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ:',
    testDatasetsDownload: 'ಪರೀಕ್ಷಾ ಡೇಟಾಸೆಟ್‌ಗಳು ಮತ್ತು WFDB ಫೈಲ್‌ಗಳು:',
    clickToDownload: 'PC ಗೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    enterPatientDetails: 'ರೋಗಿಯ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ',
    standardOverview: 'ಸ್ಟ್ಯಾಂಡರ್ಡ್ ಅವಲೋಕನ',
    hospitalDeviceLink: 'ಆಸ್ಪತ್ರೆ ಸಾಧನದ ಲಿಂಕ್',
    clinicalTrialExporter: 'ಕ್ಲಿನಿಕಲ್ ಟ್ರಯಲ್ ಎಕ್ಸ್‌ಪೋರ್ಟರ್',
    dragDropText: 'ECG ಅಥವಾ PPG ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ಡ್ರಾಗ್ ಮತ್ತು ಡ್ರಾಪ್ ಮಾಡಿ',
    orClickBrowse: 'ಅಥವಾ ನಿಮ್ಮ ಕಂಪ್ಯೂಟರ್‌ನಿಂದ ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    supportedFormats: 'ಬೆಂಬಲಿತವಾಗಿದೆ: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('cardiosense_lang') as Language
    if (saved && LANGUAGES.some((l) => l.code === saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('cardiosense_lang', lang)
  }

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en
    return dict[key] || TRANSLATIONS.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
