'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'gu' | 'mr' | 'bn' | 'kn'

export interface LanguageOption {
  code: Language
  label: string
  nativeName: string
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeName: 'English' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'gu', label: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr', label: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা' },
  { code: 'kn', label: 'Kannada', nativeName: 'ಕನ್ನಡ' },
]

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    brandName: 'CardioSense AI',
    dashboard: 'Dashboard',
    newAnalysis: 'New Analysis',
    history: 'History',
    doctorPortal: 'Doctor Portal',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    welcomeBack: 'Welcome back',
    patientMode: 'Patient Mode',
    doctorMode: 'Doctor Mode',
    adminMode: 'Admin Mode',
    uploadNewSignal: 'Upload New Signal',
    historyTrends: 'History & Trends',
    screeningReports: 'Screening Reports',
    signalType: 'Select Signal Type',
    chooseFile: 'Choose Signal File',
    analyzeNow: 'Analyze Recording Now',
    signalQuality: 'Signal Quality Score',
    heartRate: 'Heart Rate Analysis',
    aiPrediction: 'AI Model Prediction',
    downloadPdf: 'Download PDF Report',
    dateAndTime: 'Date & Time',
    filterType: 'Filter Type',
    sortBy: 'Sort By',
    recentAnalyses: 'Recent Analysis Sessions',
    hospitalMode: 'Hospital Mode',
    cardiacScreeningUpload: 'Cardiac Screening & Patient Upload',
    doctorClinicalUpload: 'Doctor Clinical Upload & Patient Intake',
    uploadSubtitle: 'Upload a single or multi-lead cardiac recording or select a pre-loaded research dataset. Attach patient details to save directly into history & doctor patient records.',
    voltage: 'Voltage',
    ecgDesc: 'Electrocardiogram electrical signal leads.',
    optical: 'Optical',
    ppgDesc: 'Photoplethysmogram blood pulse waves.',
    instantTestDatasets: 'Instant Test Datasets',
    preloadedRecordings: 'Pre-loaded research ECG/PPG recordings',
    noFilesHint: 'No local ECG/PPG files on your device? Click any pre-loaded dataset below to test the platform instantly:',
    testDatasetsDownload: 'Test Datasets & PhysioNet WFDB Files:',
    clickToDownload: 'Click to download to PC',
    enterPatientDetails: 'Enter Patient Details & Analyze Recording',
    standardOverview: 'Standard Overview',
    hospitalDeviceLink: 'Hospital Device Link (Web Serial / Oscilloscope)',
    clinicalTrialExporter: 'Clinical Trial Exporter',
    dragDropText: 'Drag & Drop ECG or PPG Recording',
    orClickBrowse: 'or click to browse from your computer',
    supportedFormats: 'Supported: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR (PhysioNet WFDB)',
    clinicalCardiacScreening: 'Clinical Cardiac Screening',
    portalActive: 'Portal Active',
    dashboardSubtitle: 'Real-time electrophysiological (ECG) and optical (PPG) screening powered by 1D-CNN deep learning with saliency Explainable AI (XAI) overlays.',
    viewHistoryRecords: 'View History Records',
    analyzeCsvHint: 'Analyze CSV, TXT, EDF clinical signals',
    trackHeartHistory: 'Track heart rate & AI confidence history',
    doctorPatientPortal: 'Doctor Patient Portal',
    reviewPatientCohorts: 'Review patient cohorts & submitted notes',
    downloadPdfReports: 'Download formatted PDF reports (i18n)',
    smartSystemAlerts: 'Smart System Alerts',
    reviewAnalysis: 'Review Analysis',
    loadingStats: 'Loading screening statistics & history...',
    loadingDashboard: 'Loading Dashboard...',
    clinicalCapabilities: 'Clinical Capabilities & AI Architecture',
    clinicalCapabilitiesSubtitle: 'End-to-end electrophysiological analysis, explainability models, and patient report export.',
    cnnTitle: '1D-CNN Deep Learning',
    cnnDesc: 'Bandpass filtered 0.5–100Hz 1D Convolutional Neural Network trained on 3,600-sample windows for automated cardiac rhythm classification.',
    cnnBadge: 'Real-time Inference (<2.0s)',
    xaiTitle: 'Explainable AI (XAI) Overlay',
    xaiDesc: 'Gradient backpropagation saliency heatmaps highlighting exact temporal regions that influenced the deep model prediction.',
    xaiBadge: 'High Clinical Transparency',
    pdfTitle: 'Multi-Language PDF Exports',
    pdfDesc: 'Download formal clinical PDF reports formatted natively in 7 languages (English, Hindi, Tamil, Telugu, Gujarati, Marathi, Bengali).',
    pdfBadge: 'Native i18n Renderer',
    statTotalAnalyses: 'Total Analyses',
    statCompletedRecordings: 'Completed recordings',
    statNormal: 'Normal',
    statNormalSinus: 'Normal sinus rhythm',
    statNeedsReview: 'Needs Review',
    statFlaggedLow: 'Flagged or low confidence',
    statPoorQuality: 'Poor Quality',
    statHighNoise: 'High noise or artifact',
    latestRecording: 'Latest Recording',
    aiRhythmClassification: 'AI Rhythm Classification',
    confidence: 'confidence',
    heartRateLabel: 'Heart Rate',
    qualityLabel: 'Quality',
    anomalyLabel: 'Anomaly',
    viewFullWaveform: 'View Full Waveform & XAI',
    liveScanner: 'Live Scanner',
    settingsProfile: 'Settings & Profile',
    signingOut: 'Signing out...',
    screeningRecordsHistory: 'Screening Records History',
  },
  hi: {
    brandName: 'कार्डियोसेंस एआई',
    dashboard: 'डैशबोर्ड',
    newAnalysis: 'नया विश्लेषण',
    history: 'इतिहास',
    doctorPortal: 'डॉक्टर पोर्टल',
    adminPanel: 'एडमिन पैनल',
    logout: 'लॉगआउट',
    welcomeBack: 'नमस्ते, स्वागत है',
    patientMode: 'मरीज़ मोड',
    doctorMode: 'डॉक्टर मोड',
    adminMode: 'एडमिन मोड',
    uploadNewSignal: 'नया सिग्नल अपलोड करें',
    historyTrends: 'इतिहास और रुझान',
    screeningReports: 'स्क्रीनिंग रिपोर्ट',
    signalType: 'सिग्नल प्रकार चुनें',
    chooseFile: 'सिग्नल फ़ाइल चुनें',
    analyzeNow: 'अब विश्लेषण करें',
    signalQuality: 'सिग्नल गुणवत्ता स्कोर',
    heartRate: 'हृदय गति विश्लेषण',
    aiPrediction: 'एआई मॉडल भविष्यवाणी',
    downloadPdf: 'पीडीएफ रिपोर्ट डाउनलोड करें',
    dateAndTime: 'दिनांक और समय',
    filterType: 'फ़िल्टर प्रकार',
    sortBy: 'क्रमबद्ध करें',
    recentAnalyses: 'हाल के विश्लेषण सत्र',
    hospitalMode: 'अस्पताल मोड',
    cardiacScreeningUpload: 'हृदय स्क्रीनिंग एवं मरीज अपलोड',
    doctorClinicalUpload: 'डॉक्टर क्लिनिकल अपलोड एवं मरीज प्रविष्टि',
    uploadSubtitle: 'एकल या मल्टी-लीड कार्डिएक रिकॉर्डिंग अपलोड करें या प्री-लोड किए गए शोध डेटासेट का चयन करें। इतिहास और डॉक्टर मरीज रिकॉर्ड में सहेजने के लिए विवरण संलग्न करें।',
    voltage: 'वोल्टेज',
    ecgDesc: 'इलेक्ट्रोकार्डियोग्राम विद्युत सिग्नल लीड्स।',
    optical: 'ऑप्टिकल',
    ppgDesc: 'फोटोप्लेथिस्मोग्राम रक्त पल्स तरंगें।',
    instantTestDatasets: 'त्वरित परीक्षण डेटासेट',
    preloadedRecordings: 'प्री-लोड किए गए शोध ईसीजी/पीपीजी रिकॉर्डिंग',
    noFilesHint: 'क्या आपके डिवाइस पर ईसीजी/पीपीजी फ़ाइलें नहीं हैं? मंच का तुरंत परीक्षण करने के लिए नीचे किसी भी डेटासेट पर क्लिक करें:',
    testDatasetsDownload: 'परीक्षण डेटासेट एवं फिजियोनेट WFDB फ़ाइलें:',
    clickToDownload: 'पीसी पर डाउनलोड करने के लिए क्लिक करें',
    enterPatientDetails: 'मरीज का विवरण दर्ज करें और रिकॉर्डिंग का विश्लेषण करें',
    standardOverview: 'मानक अवलोकन',
    hospitalDeviceLink: 'अस्पताल उपकरण लिंक (वेब सीरियल / ऑसिस्कोप)',
    clinicalTrialExporter: 'क्लिनिकल ट्रायल निर्यातक',
    dragDropText: 'ईसीजी या पीपीजी रिकॉर्डिंग ड्रैग और ड्रॉप करें',
    orClickBrowse: 'या अपने कंप्यूटर से ब्राउज़ करने के लिए क्लिक करें',
    supportedFormats: 'समर्थित: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR (फिजियोनेट WFDB)',
    clinicalCardiacScreening: 'क्लिनिकल कार्डिएक स्क्रीनिंग',
    portalActive: 'पोर्टल सक्रिय',
    dashboardSubtitle: 'रियल-टाइम इलेक्ट्रोफिज़ियोलॉजिकल (ईसीजी) और ऑप्टिकल (पीपीजी) स्क्रीनिंग 1D-CNN डीप लर्निंग द्वारा संचालित।',
    viewHistoryRecords: 'इतिहास रिकॉर्ड देखें',
    analyzeCsvHint: 'CSV, TXT, EDF क्लिनिकल सिग्नल विश्लेषण करें',
    trackHeartHistory: 'हृदय गति और एआई कॉन्फिडेंस इतिहास ट्रैक करें',
    doctorPatientPortal: 'डॉक्टर मरीज़ पोर्टल',
    reviewPatientCohorts: 'मरीज़ समूह और नोट समीक्षा करें',
    downloadPdfReports: 'फॉर्मेटेड पीडीएफ रिपोर्ट डाउनलोड करें',
    smartSystemAlerts: 'स्मार्ट सिस्टम अलर्ट',
    reviewAnalysis: 'विश्लेषण समीक्षा करें',
    loadingStats: 'स्क्रीनिंग आँकड़े और इतिहास लोड हो रहा है...',
    loadingDashboard: 'डैशबोर्ड लोड हो रहा है...',
    clinicalCapabilities: 'क्लिनिकल क्षमताएं और एआई आर्किटेक्चर',
    clinicalCapabilitiesSubtitle: 'एंड-टू-एंड इलेक्ट्रोफिज़ियोलॉजिकल विश्लेषण, एक्सप्लेनेबिलिटी मॉडल और रिपोर्ट निर्यात।',
    cnnTitle: '1D-CNN डीप लर्निंग',
    cnnDesc: 'स्वचालित कार्डियक रिदम वर्गीकरण के लिए 3,600-सैंपल विंडो पर प्रशिक्षित बैंडपास फ़िल्टर्ड 0.5–100Hz 1D CNN।',
    cnnBadge: 'रियल-टाइम अनुमान (<2.0s)',
    xaiTitle: 'एक्सप्लेनेबल एआई (XAI) ओवरले',
    xaiDesc: 'ग्रेडिएंट बैकप्रॉपेगेशन सैलिएंसी हीटमैप जो डीप मॉडल भविष्यवाणी को प्रभावित करने वाले क्षेत्रों को हाइलाइट करती है।',
    xaiBadge: 'उच्च क्लिनिकल पारदर्शिता',
    pdfTitle: 'बहुभाषी पीडीएफ निर्यात',
    pdfDesc: '7 भाषाओं में औपचारिक क्लिनिकल पीडीएफ रिपोर्ट डाउनलोड करें।',
    pdfBadge: 'नेटिव i18n रेंडरर',
    statTotalAnalyses: 'कुल विश्लेषण',
    statCompletedRecordings: 'पूर्ण रिकॉर्डिंग',
    statNormal: 'सामान्य',
    statNormalSinus: 'सामान्य साइनस रिदम',
    statNeedsReview: 'समीक्षा आवश्यक',
    statFlaggedLow: 'फ्लैग या कम कॉन्फिडेंस',
    statPoorQuality: 'खराब गुणवत्ता',
    statHighNoise: 'उच्च शोर या आर्टिफैक्ट',
    latestRecording: 'नवीनतम रिकॉर्डिंग',
    aiRhythmClassification: 'एआई रिदम वर्गीकरण',
    confidence: 'कॉन्फिडेंस',
    heartRateLabel: 'हृदय गति',
    qualityLabel: 'गुणवत्ता',
    anomalyLabel: 'विसंगति',
    viewFullWaveform: 'पूर्ण वेवफॉर्म और XAI देखें',
    liveScanner: 'लाइव स्कैनर',
    settingsProfile: 'सेटिंग्स और प्रोफाइल',
    signingOut: 'लॉग आउट हो रहा है...',
    screeningRecordsHistory: 'स्क्रीनिंग रिकॉर्ड इतिहास',
  },
  ta: {
    brandName: 'கார்டியோசென்ஸ் AI',
    dashboard: 'டாஷ்போர்டு',
    newAnalysis: 'புதிய பகுப்பாய்வு',
    history: 'வரலாறு',
    doctorPortal: 'மருத்துவர் தளம்',
    adminPanel: 'நிர்வாகக் குழு',
    logout: 'வெளியேறு',
    welcomeBack: 'நல்வரவு',
    patientMode: 'நோயாளி பயன்முறை',
    doctorMode: 'மருத்துவர் பயன்முறை',
    adminMode: 'நிர்வாகி பயன்முறை',
    uploadNewSignal: 'புதிய சமிக்ஞையைப் பதிவேற்று',
    historyTrends: 'வரலாறு மற்றும் போக்குகள்',
    screeningReports: 'பரிசோதனை அறிக்கைகள்',
    signalType: 'சமிக்ஞை வகையைத் தேர்ந்தெடு',
    chooseFile: 'கோப்பைத் தேர்ந்தெடு',
    analyzeNow: 'இப்போது பகுப்பாய்வு செய்',
    signalQuality: 'சமிக்ஞை தர மதிப்பீடு',
    heartRate: 'இதய துடிப்பு பகுப்பாய்வு',
    aiPrediction: 'AI கணிப்பு',
    downloadPdf: 'PDF அறிக்கையைப் பதிவிறக்கு',
    dateAndTime: 'தேதி மற்றும் நேரம்',
    filterType: 'வடிகட்டி வகை',
    sortBy: 'வரிசைப்படுத்து',
    recentAnalyses: 'சமீபத்திய பகுப்பாய்வுகள்',
    hospitalMode: 'மருத்துவமனை முறை',
    cardiacScreeningUpload: 'இதய பரிசோதனை & நோயாளி பதிவேற்றம்',
    doctorClinicalUpload: 'மருத்துவர் மருத்துவ பதிவேற்றம்',
    uploadSubtitle: 'கார்டியாக் பதிவை பதிவேற்றவும் அல்லது ஆராய்ச்சி தரவுத்தொகுப்பைத் தேர்ந்தெடுக்கவும்.',
    voltage: 'மின்னழுத்தம்',
    ecgDesc: 'எலக்ட்ரோ கார்டியோகிராம் மின்சார சமிக்ஞைகள்.',
    optical: 'ஒளியியல்',
    ppgDesc: 'ஃபோட்டோபிளெதிஸ்மோகிராம் இரத்த துடிப்பு அலைகள்.',
    instantTestDatasets: 'உடனடி சோதனை தரவுத்தொகுப்புகள்',
    preloadedRecordings: 'முன்பே ஏற்றப்பட்ட ஆராய்ச்சி பதிவுகள்',
    noFilesHint: 'கோப்புகள் இல்லையா? உடனடியாக சோதிக்க கீழே உள்ள தரவுத்தொகுப்பைக் கிளிக் செய்யவும்:',
    testDatasetsDownload: 'சோதனை தரவுத்தொகுப்புகள் & WFDB கோப்புகள்:',
    clickToDownload: 'கணினியில் பதிவிறக்க கிளிக் செய்யவும்',
    enterPatientDetails: 'நோயாளி விவரங்களை உள்ளிட்டு பகுப்பாய்வு செய்யவும்',
    standardOverview: 'தரமான பார்வை',
    hospitalDeviceLink: 'மருத்துவமனை சாதன இணைப்பு',
    clinicalTrialExporter: 'மருத்துவ சோதனை ஏற்றுமதியாளர்',
    dragDropText: 'ECG அல்லது PPG பதிவை இழுத்து விடவும்',
    orClickBrowse: 'அல்லது கணினியிலிருந்து தேர்ந்தெடுக்க கிளிக் செய்யவும்',
    supportedFormats: 'ஆதரிக்கப்படும் வடிவங்கள்: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
    clinicalCardiacScreening: 'மருத்துவ இதய பரிசோதனை',
    portalActive: 'போர்டல் செயலில் உள்ளது',
    dashboardSubtitle: '1D-CNN ஆழமான கற்றல் மூலம் இயக்கப்படும் ECG மற்றும் PPG பரிசோதனை.',
    viewHistoryRecords: 'வரலாறு பதிவுகளைப் பார்க்கவும்',
    analyzeCsvHint: 'CSV, TXT, EDF சிகனல்களை பகுப்பாய்வு செய்யவும்',
    trackHeartHistory: 'இதய துடிப்பு மற்றும் AI நம்பிக்கை வரலாற்றை கண்காணிக்கவும்',
    doctorPatientPortal: 'மருத்துவர் நோயாளி போர்டல்',
    reviewPatientCohorts: 'நோயாளி குழுக்கள் மற்றும் குறிப்புகளை மதிப்பாய்வு செய்யவும்',
    downloadPdfReports: 'வடிவமைக்கப்பட்ட PDF அறிக்கைகளை பதிவிறக்கவும்',
    smartSystemAlerts: 'நுண்ணறிவு அமைப்பு எச்சரிக்கைகள்',
    reviewAnalysis: 'பகுப்பாய்வை மதிப்பாய்வு செய்யவும்',
    loadingStats: 'புள்ளிவிவரங்கள் ஏற்றப்படுகின்றன...',
    loadingDashboard: 'டாஷ்போர்டு ஏற்றப்படுகிறது...',
    clinicalCapabilities: 'மருத்துவ திறன்கள் மற்றும் AI கட்டமைப்பு',
    clinicalCapabilitiesSubtitle: 'முழுமையான ECG பகுப்பாய்வு, விளக்கப் பொருள் மாதிரிகள் மற்றும் அறிக்கை ஏற்றுமதி.',
    cnnTitle: '1D-CNN ஆழமான கற்றல்',
    cnnDesc: 'தானியங்கி இதய கட்டளை வகைப்பாடுக்காக 3,600 மாதிரி சாளரங்களில் பயிற்சி பெற்ற CNN.',
    cnnBadge: 'நிகழ்நேர அனுமான (<2.0s)',
    xaiTitle: 'விளக்கக்கூடிய AI (XAI) மேலடுக்கு',
    xaiDesc: 'மாதிரி கணிப்பை பாதித்த காலப் பகுதிகளை முன்னிலைப்படுத்தும் சாலியன்சி வரைபடங்கள்.',
    xaiBadge: 'உயர் மருத்துவ வெளிப்படைத்தன்மை',
    pdfTitle: 'பல மொழி PDF ஏற்றுமதிகள்',
    pdfDesc: '7 மொழிகளில் உருவாக்கப்பட்ட மருத்துவ PDF அறிக்கைகளை பதிவிறக்கவும்.',
    pdfBadge: 'நேட்டிவ் i18n ரெண்டரர்',
    statTotalAnalyses: 'மொத்த பகுப்பாய்வுகள்',
    statCompletedRecordings: 'முடிந்த பதிவுகள்',
    statNormal: 'சாதாரண',
    statNormalSinus: 'சாதாரண சைனஸ் தாளம்',
    statNeedsReview: 'மதிப்பாய்வு தேவை',
    statFlaggedLow: 'கொடியிடப்பட்ட அல்லது குறைந்த நம்பிக்கை',
    statPoorQuality: 'மோசமான தரம்',
    statHighNoise: 'அதிக சத்தம் அல்லது கலைப்பு',
    latestRecording: 'சமீபத்திய பதிவு',
    aiRhythmClassification: 'AI இதய தாள வகைப்பாடு',
    confidence: 'நம்பிக்கை',
    heartRateLabel: 'இதய துடிப்பு',
    qualityLabel: 'தரம்',
    anomalyLabel: 'முரண்பாடு',
    viewFullWaveform: 'முழு அலை வடிவம் மற்றும் XAI பார்க்கவும்',
    liveScanner: 'நேரடி ஸ்கானர்',
    settingsProfile: 'அமைப்புகள் மற்றும் ப்ரொபைல்',
    signingOut: 'வெளியேறுகிறது...',
    screeningRecordsHistory: 'பரிசோதனை பதிவு வரலாறு',
  },
  te: {
    brandName: 'కార్డియోసెన్స్ AI',
    dashboard: 'డాష్‌బోర్డ్',
    newAnalysis: 'కొత్త విశ్లేషణ',
    history: 'చరిత్ర',
    doctorPortal: 'వైద్యుల పోర్టల్',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    logout: 'లాగ్‌అవుట్',
    welcomeBack: 'స్వాగతం',
    patientMode: 'పేషెంట్ మోడ్',
    doctorMode: 'డాక్టర్ మోడ్',
    adminMode: 'అడ్మిన్ మోడ్',
    uploadNewSignal: 'కొత్త సిగ్నల్ అప్‌లోడ్ చేయండి',
    historyTrends: 'చరిత్ర మరియు ట్రెండ్‌లు',
    screeningReports: 'స్క్రీనింగ్ రిపోర్టులు',
    signalType: 'సిగ్నల్ రకాన్ని ఎంచుకోండి',
    chooseFile: 'ఫైల్‌ను ఎంచుకోండి',
    analyzeNow: 'ఇప్పుడే విశ్లేషించండి',
    signalQuality: 'సిగ్నల్ క్వాలిటీ స్కోర్',
    heartRate: 'గుండె వేగం విశ్లేషణ',
    aiPrediction: 'AI అంచనా',
    downloadPdf: 'PDF నివేదికను డౌన్‌లోడ్ చేయండి',
    dateAndTime: 'తేదీ మరియు సమయం',
    filterType: 'ఫిల్టర్ రకం',
    sortBy: 'క్రమబద్ధీకరించు',
    recentAnalyses: 'ఇటీవలి విశ్లేషణలు',
    hospitalMode: 'హాస్పిటల్ మోడ్',
    cardiacScreeningUpload: 'కార్డియాక్ స్క్రీనింగ్ & పేషెంట్ అప్‌లోడ్',
    doctorClinicalUpload: 'డాక్టర్ క్లినికల్ అప్‌లోడ్',
    uploadSubtitle: 'కార్డియాక్ రికార్డింగ్‌ను అప్‌లోడ్ చేయండి లేదా రీసెర్చ్ డేటాసెట్‌ను ఎంచుకోండి.',
    voltage: 'వోల్టేజ్',
    ecgDesc: 'ఎలక్ట్రోకార్డియోగామ్ ఎలక్ట్రికల్ సిగ్నల్స్.',
    optical: 'ఆప్టికల్',
    ppgDesc: 'ఫోటోప్లెథిస్మోగ్రామ్ రక్త పల్స్ తరంగాలు.',
    instantTestDatasets: 'తక్షణ పరీక్ష డేటాసెట్‌లు',
    preloadedRecordings: 'ముందుగా లోడ్ చేసిన పరిశోధన రికార్డింగ్‌లు',
    noFilesHint: 'ఫైల్‌లు లేవా? ప్లాట్‌ఫారమ్‌ను పరీక్షించడానికి కింద క్లిక్ చేయండి:',
    testDatasetsDownload: 'పరీక్ష డేటాసెట్‌లు & WFDB ఫైల్‌లు:',
    clickToDownload: 'PC లోకి డౌన్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    enterPatientDetails: 'పేషెంట్ వివరాలను నమోదు చేసి విశ్లేషించండి',
    standardOverview: 'స్టాండర్డ్ ఓవర్‌వ్యూ',
    hospitalDeviceLink: 'హాస్పిటల్ పరికర లింక్',
    clinicalTrialExporter: 'క్లినికల్ ట్రయల్ ఎక్స్‌పోర్టర్',
    dragDropText: 'ECG లేదా PPG రికార్డింగ్‌ను డ్రాగ్ & డ్రాప్ చేయండి',
    orClickBrowse: 'లేదా కంప్యూటర్ నుండి బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    supportedFormats: 'మద్దతు ఉన్న రకాలు: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
    clinicalCardiacScreening: 'క్లినికల్ కార్డియాక్ స్క్రీనింగ్',
    portalActive: 'పోర్టల్ యాక్టివ్',
    dashboardSubtitle: '1D-CNN డీప్ లెర్నింగ్ ద్వారా నిజ-సమయ ECG మరియు PPG స్క్రీనింగ్.',
    viewHistoryRecords: 'చరిత్ర రికార్డులు చూడండి',
    analyzeCsvHint: 'CSV, TXT, EDF క్లినికల్ సిగ్నల్‌లు విశ్లేషించండి',
    trackHeartHistory: 'గుండె వేగం & AI విశ్వాసం చరిత్ర ట్రాక్ చేయండి',
    doctorPatientPortal: 'డాక్టర్ పేషెంట్ పోర్టల్',
    reviewPatientCohorts: 'పేషెంట్ సమూహాలు & నోట్లు సమీక్షించండి',
    downloadPdfReports: 'ఫార్మాటెడ్ PDF నివేదికలు డౌన్‌లోడ్ చేయండి',
    smartSystemAlerts: 'స్మార్ట్ సిస్టమ్ హెచ్చరికలు',
    reviewAnalysis: 'విశ్లేషణ సమీక్షించండి',
    loadingStats: 'స్క్రీనింగ్ గణాంకాలు లోడ్ అవుతున్నాయి...',
    loadingDashboard: 'డాష్‌బోర్డ్ లోడ్ అవుతోంది...',
    clinicalCapabilities: 'క్లినికల్ సామర్థ్యాలు & AI ఆర్కిటెక్చర్',
    clinicalCapabilitiesSubtitle: 'ఎండ్-టు-ఎండ్ ECG విశ్లేషణ, వివరణ మోడళ్లు మరియు రిపోర్ట్ ఎగుమతి.',
    cnnTitle: '1D-CNN డీప్ లెర్నింగ్',
    cnnDesc: 'స్వయంచాలిత కార్డియాక్ రిథమ్ వర్గీకరణ కోసం 3,600-నమూనా విండోలలో శిక్షణ పొందిన CNN.',
    cnnBadge: 'రియల్-టైమ్ ఇన్ఫరెన్స్ (<2.0s)',
    xaiTitle: 'వివరణాత్మక AI (XAI) పొర',
    xaiDesc: 'డీప్ మోడల్ అంచనాను ప్రభావితం చేసిన కాల ప్రాంతాలను హైలైట్ చేసే సాలియన్సీ హీట్‌మాప్‌లు.',
    xaiBadge: 'అధిక క్లినికల్ పారదర్శకత',
    pdfTitle: 'బహుభాషా PDF ఎగుమతులు',
    pdfDesc: '7 భాషలలో ఫార్మాట్ చేసిన క్లినికల్ PDF నివేదికలు డౌన్‌లోడ్ చేయండి.',
    pdfBadge: 'నేటివ్ i18n రెండరర్',
    statTotalAnalyses: 'మొత్తం విశ్లేషణలు',
    statCompletedRecordings: 'పూర్తయిన రికార్డింగ్‌లు',
    statNormal: 'సాధారణ',
    statNormalSinus: 'సాధారణ సైనస్ రిథమ్',
    statNeedsReview: 'సమీక్ష అవసరం',
    statFlaggedLow: 'ఫ్లాగ్ లేదా తక్కువ విశ్వాసం',
    statPoorQuality: 'నాసిరకం నాణ్యత',
    statHighNoise: 'అధిక శబ్దం లేదా ఆర్టిఫ్యాక్ట్',
    latestRecording: 'తాజా రికార్డింగ్',
    aiRhythmClassification: 'AI రిథమ్ వర్గీకరణ',
    confidence: 'విశ్వాసం',
    heartRateLabel: 'గుండె వేగం',
    qualityLabel: 'నాణ్యత',
    anomalyLabel: 'అసాధారణత',
    viewFullWaveform: 'పూర్తి వేవ్‌ఫారమ్ & XAI చూడండి',
    liveScanner: 'లైవ్ స్క్యానర్',
    settingsProfile: 'సెట్టింగ్‌లు & ప్రొఫైల్',
    signingOut: 'సైన్ అవుతున్నారు...',
    screeningRecordsHistory: 'స్క్రీనింగ్ రికార్డుల చరిత్ర',
  },
  gu: {
    brandName: 'કાર્ડિઓસેન્સ AI',
    dashboard: 'ડેશબોર્ડ',
    newAnalysis: 'નવું વિશ્લેષણ',
    history: 'ઇતિહાસ',
    doctorPortal: 'ડૉક્ટર પોર્ટલ',
    adminPanel: 'એડમિન પેનલ',
    logout: 'લૉગઆઉટ',
    welcomeBack: 'સ્વાગત છે',
    patientMode: 'દર્દી મોડ',
    doctorMode: 'ડૉક્ટર મોડ',
    adminMode: 'એડમિન મોડ',
    uploadNewSignal: 'નવો સિગ્નલ અપલોડ કરો',
    historyTrends: 'ઇતિહાસ અને પ્રવાહો',
    screeningReports: 'સ્ક્રીનીંગ રિપોર્ટ્સ',
    signalType: 'સિગ્નલ પ્રકાર પસંદ કરો',
    chooseFile: 'સિગ્નલ ફાઇલ પસંદ કરો',
    analyzeNow: 'હવે વિશ્લેષણ કરો',
    signalQuality: 'સિગ્નલ ગુણવત્તા સ્કોર',
    heartRate: 'હૃદયના ધબકારાનું વિશ્લેષણ',
    aiPrediction: 'AI મોડેલ આગાહી',
    downloadPdf: 'PDF રિપોર્ટ ડાઉનલોડ કરો',
    dateAndTime: 'તારીખ અને સમય',
    filterType: 'ફિલ્ટર પ્રકાર',
    sortBy: 'ક્રમમાં ગોઠવો',
    recentAnalyses: 'તાજેતરના વિશ્લેષણ',
    hospitalMode: 'હોસ્પિટલ મોડ',
    cardiacScreeningUpload: 'હૃદય સ્ક્રીનીંગ અને દર્દી અપલોડ',
    doctorClinicalUpload: 'ડૉક્ટર ક્લિનિકલ અપલોડ',
    uploadSubtitle: 'કાર્ડિયાક રેકોર્ડિંગ અપલોડ કરો અથવા રિસર્ચ ડેટાસેટ પસંદ કરો.',
    voltage: 'વોલ્ટેજ',
    ecgDesc: 'ઇલેક્ટ્રોકાર્ડિયોગ્રામ સિગ્નલ લાઇન.',
    optical: 'ઓપ્ટિકલ',
    ppgDesc: 'ફોટોપ્લેથિસ્મોગ્રામ પલ્સ વેવ્સ.',
    instantTestDatasets: 'ઝડપી પરીક્ષણ ડેટાસેટ્સ',
    preloadedRecordings: 'પ્રી-લોડેડ સંશોધન રેકોર્ડિંગ્સ',
    noFilesHint: 'ફાઇલો નથી? પ્લેટફોર્મ ચકાસવા માટે નીચે કિલક કરો:',
    testDatasetsDownload: 'ટેસ્ટ ડેટાસેટ્સ અને WFDB ફાઇલો:',
    clickToDownload: 'પીસી પર ડાઉનલોડ કરવા ક્લિક કરો',
    enterPatientDetails: 'દર્દીની વિગતો દાખલ કરો અને વિશ્લેષણ કરો',
    standardOverview: 'સામાન્ય વિહંગાવલોકન',
    hospitalDeviceLink: 'હોસ્પિટલ ડિવાઇસ લિંક',
    clinicalTrialExporter: 'ક્લિનિકલ ટ્રાયલ એક્સપોર્ટર',
    dragDropText: 'ECG અથવા PPG રેકોર્ડિંગ ડ્રેગ અને ડ્રોપ કરો',
    orClickBrowse: 'અથવા તમારા કમ્પ્યુટરથી બ્રાઉઝ કરવા માટે કિલક કરો',
    supportedFormats: 'સપોર્ટેડ: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
    clinicalCardiacScreening: 'ક્લિનિકલ કાર્ડિયાક સ્ક્રીનિંગ',
    portalActive: 'પોર્ટલ સક્રિય',
    dashboardSubtitle: '1D-CNN ડીપ લર્નિંગ દ્વારા રીઅલ-ટાઇમ ECG અને PPG સ્ક્રીનિંગ.',
    viewHistoryRecords: 'ઇતિહાસ રેકોર્ડ જુઓ',
    analyzeCsvHint: 'CSV, TXT, EDF ક્લિનિકલ સિગ્નલ વિશ્લેષણ કરો',
    trackHeartHistory: 'હૃદય ગતિ અને AI કૉન્ફિડન્સ ઇતિહાસ ટ્રૅક કરો',
    doctorPatientPortal: 'ડૉક્ટર દર્દી પોર્ટલ',
    reviewPatientCohorts: 'દર્દી જૂથ અને નોંધ સમીક્ષા કરો',
    downloadPdfReports: 'ફૉર્મેટ કરેલ PDF રિપોર્ટ ડાઉનલોડ કરો',
    smartSystemAlerts: 'સ્માર્ટ સિસ્ટમ ચેતવણીઓ',
    reviewAnalysis: 'વિશ્લેષણ સમીક્ષા કરો',
    loadingStats: 'સ્ક્રીનિંગ આંકડા લોડ થઈ રહ્યા છે...',
    loadingDashboard: 'ડૅશબૉર્ડ લોડ થઈ રહ્યું છે...',
    clinicalCapabilities: 'ક્લિનિકલ ક્ષમતાઓ અને AI આર્કિટેક્ચર',
    clinicalCapabilitiesSubtitle: 'એન્ડ-ટૂ-એન્ડ ECG વિશ્લેષણ, સ્પષ્ટીકરણ મૉડેલ અને અહેવાલ નિકાસ.',
    cnnTitle: '1D-CNN ડીપ લર્નિંગ',
    cnnDesc: 'સ્વચાલિત કાર્ડિયાક રિધમ વર્ગીકરણ માટે 3,600-નમૂના વિન્ડોઝ પર CNN.',
    cnnBadge: 'રીઅલ-ટાઇમ અનુમાન (<2.0s)',
    xaiTitle: 'સ્પષ્ટ AI (XAI) ઓવરલે',
    xaiDesc: 'ડીપ મૉડેલ ભવિષ્યવાણીને પ્રભાવિત કરતા ટેમ્પોરલ ક્ષેત્રોને પ્રકાશિત કરતા સ્ૅલિઅન્સી હીટ-મૅપ.',
    xaiBadge: 'ઉચ્ચ ક્લિનિકલ પારદર્શિતા',
    pdfTitle: 'બહુભાષી PDF નિકાસ',
    pdfDesc: '7 ભાષાઓમાં ક્લિનિકલ PDF અહેવાલ ડાઉનલોડ કરો.',
    pdfBadge: 'નેટિવ i18n રેન્ડરર',
    statTotalAnalyses: 'કુલ વિશ્લેષણ',
    statCompletedRecordings: 'પૂર્ણ રેકોર્ડિંગ',
    statNormal: 'સામાન્ય',
    statNormalSinus: 'સામાન્ય સાઇનસ રિધમ',
    statNeedsReview: 'સમીક્ષા જરૂરી',
    statFlaggedLow: 'ફ્લેગ અથવા ઓછો આત્મવિશ્વાસ',
    statPoorQuality: 'ખરાબ ગુણવત્તા',
    statHighNoise: 'ઉચ્ચ અવાજ અથવા આર્ટિફૅક્ટ',
    latestRecording: 'તાજી રેકોર્ડિંગ',
    aiRhythmClassification: 'AI રિધમ વર્ગીકરણ',
    confidence: 'કૉન્ફિડન્સ',
    heartRateLabel: 'હૃદય ગતિ',
    qualityLabel: 'ગુણવત્તા',
    anomalyLabel: 'અસ્વાભાવિકતા',
    viewFullWaveform: 'સંપૂર્ણ વેવ-ફૉર્મ અને XAI જુઓ',
    liveScanner: 'લાઇવ સ્કેનર',
    settingsProfile: 'સેટિંગ્સ અને પ્રોફાઇલ',
    signingOut: 'સાઇન આઉટ થઈ રહ્યું છે...',
    screeningRecordsHistory: 'સ્ક્રીનિંગ રેકોર્ડ ઇતિહાસ',
  },
  mr: {
    brandName: 'कार्डिओसेन्स AI',
    dashboard: 'डॅशबोर्ड',
    newAnalysis: 'नवीन विश्लेषण',
    history: 'इतिहास',
    doctorPortal: 'डॉक्टर पोर्टल',
    adminPanel: 'ॲडमिन पॅनेल',
    logout: 'लॉगआउट',
    welcomeBack: 'सुस्वागतम',
    patientMode: 'रुग्ण मोड',
    doctorMode: 'डॉक्टर मोड',
    adminMode: 'ॲडमिन मोड',
    uploadNewSignal: 'नवीन सिग्नल अपलोड करा',
    historyTrends: 'इतिहास आणि ट्रेंड',
    screeningReports: 'स्क्रीनिंग अहवाल',
    signalType: 'सिग्नल प्रकार निवडा',
    chooseFile: 'सिग्नल फाइल निवडा',
    analyzeNow: 'आता विश्लेषण करा',
    signalQuality: 'सिग्नल गुणवत्ता स्कोर',
    heartRate: 'हृदयगती विश्लेषण',
    aiPrediction: 'AI मॉडेल भाकीत',
    downloadPdf: 'PDF अहवाल डाउनलोड करा',
    dateAndTime: 'दिनांक आणि वेळ',
    filterType: 'फिल्टर प्रकार',
    sortBy: 'क्रमवारी लावा',
    recentAnalyses: 'नुकतेच केलेले विश्लेषण',
    hospitalMode: 'हॉस्पिटल मोड',
    cardiacScreeningUpload: 'हृदय तपासणी आणि रुग्ण अपलोड',
    doctorClinicalUpload: 'डॉक्टर क्लिनिकल अपलोड',
    uploadSubtitle: 'कार्डियाक रेकॉर्डिंग अपलोड करा किंवा संशोधन डेटासेट निवडा.',
    voltage: 'व्होल्टेज',
    ecgDesc: 'इलेक्ट्रोकार्डिओग्राम इलेक्ट्रिकल सिग्नल.',
    optical: 'ऑप्टिकल',
    ppgDesc: 'फोटोप्लेथिस्मोग्राम रक्त लहरी.',
    instantTestDatasets: 'झटपट चाचणी डेटासेट',
    preloadedRecordings: 'प्री-लोड केलेले संशोधन रेकॉर्डिंग',
    noFilesHint: 'फायली नाहीत? प्लॅटफॉर्म तपासण्यासाठी खाली क्लिक करा:',
    testDatasetsDownload: 'चाचणी डेटासेट आणि WFDB फायली:',
    clickToDownload: 'पीसी वर डाउनलोड करण्यासाठी क्लिक करा',
    enterPatientDetails: 'रुग्णाची माहिती भरा आणि विश्लेषण करा',
    standardOverview: 'मानक विहंगावलोकन',
    hospitalDeviceLink: 'हॉस्पिटल डिव्हाइस लिंक',
    clinicalTrialExporter: 'क्लिनिकल ट्रायल एक्सपोर्टर',
    dragDropText: 'ECG किंवा PPG रेकॉर्डिंग ड्रॅग आणि ड्रॉप करा',
    orClickBrowse: 'किंवा संगणकावरून निवडण्यासाठी क्लिक करा',
    supportedFormats: 'समर्थित: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
    clinicalCardiacScreening: 'क्लिनिकल कार्डिएक स्क्रीनिंग',
    portalActive: 'पोर्टल सक्रिय',
    dashboardSubtitle: '1D-CNN डीप लर्निंगद्वारे रिअल-टाइम ECG आणि PPG स्क्रीनिंग.',
    viewHistoryRecords: 'इतिहास नोंदी पहा',
    analyzeCsvHint: 'CSV, TXT, EDF क्लिनिकल सिग्नल्सचे विश्लेषण करा',
    trackHeartHistory: 'हृदयगती आणि AI विश्वास इतिहास ट्रॅक करा',
    doctorPatientPortal: 'डॉक्टर रुग्ण पोर्टल',
    reviewPatientCohorts: 'रुग्ण गट आणि नोट्स तपासा',
    downloadPdfReports: 'फॉर्मेटेड PDF अहवाल डाउनलोड करा',
    smartSystemAlerts: 'स्मार्ट सिस्टम सूचना',
    reviewAnalysis: 'विश्लेषण तपासा',
    loadingStats: 'स्क्रीनिंग आकडेवारी लोड होत आहे...',
    loadingDashboard: 'डॅशबोर्ड लोड होत आहे...',
    clinicalCapabilities: 'क्लिनिकल क्षमता आणि AI आर्किटेक्चर',
    clinicalCapabilitiesSubtitle: 'एंड-टू-एंड ECG विश्लेषण, स्पष्टीकरण मॉडेल आणि अहवाल निर्यात.',
    cnnTitle: '1D-CNN डीप लर्निंग',
    cnnDesc: 'स्वयंचलित कार्डियाक रिदम वर्गीकरणासाठी 3,600-नमुना विंडोवर CNN.',
    cnnBadge: 'रिअल-टाइम अनुमान (<2.0s)',
    xaiTitle: 'स्पष्टीकरणयोग्य AI (XAI) ओव्हरले',
    xaiDesc: 'डीप मॉडेल अंदाजावर परिणाम करणाऱ्या कालिक प्रदेशांना हायलाइट करणारे हीटमॅप.',
    xaiBadge: 'उच्च क्लिनिकल पारदर्शकता',
    pdfTitle: 'बहुभाषिक PDF निर्यात',
    pdfDesc: '7 भाषांमध्ये क्लिनिकल PDF अहवाल डाउनलोड करा.',
    pdfBadge: 'नेटिव्ह i18n रेंडरर',
    statTotalAnalyses: 'एकूण विश्लेषणे',
    statCompletedRecordings: 'पूर्ण रेकॉर्डिंग',
    statNormal: 'सामान्य',
    statNormalSinus: 'सामान्य सायनस रिदम',
    statNeedsReview: 'पुनरावलोकन आवश्यक',
    statFlaggedLow: 'फ्लॅग किंवा कमी विश्वास',
    statPoorQuality: 'खराब गुणवत्ता',
    statHighNoise: 'उच्च आवाज किंवा आर्टिफॅक्ट',
    latestRecording: 'नवीनतम रेकॉर्डिंग',
    aiRhythmClassification: 'AI रिदम वर्गीकरण',
    confidence: 'विश्वास',
    heartRateLabel: 'हृदयगती',
    qualityLabel: 'गुणवत्ता',
    anomalyLabel: 'विसंगती',
    viewFullWaveform: 'पूर्ण वेवफॉर्म आणि XAI पहा',
    liveScanner: 'लाइव्ह स्कॅनर',
    settingsProfile: 'सेटिंग्स आणि प्रोफाइल',
    signingOut: 'साइन आउट होत आहे...',
    screeningRecordsHistory: 'स्क्रीनिंग नोंदी इतिहास',
  },
  bn: {
    brandName: 'কার্ডিওসেন্স AI',
    dashboard: 'ড্যাশবোর্ড',
    newAnalysis: 'নতুন বিশ্লেষণ',
    history: 'ইতিহাস',
    doctorPortal: 'ডাক্তার পোর্টাল',
    adminPanel: 'অ্যাডমিন প্যানেল',
    logout: 'লগআউট',
    welcomeBack: 'স্বাগতম',
    patientMode: 'রোগী মোড',
    doctorMode: 'ডাক্তার মোড',
    adminMode: 'অ্যাডমিন মোড',
    uploadNewSignal: 'নতুন সংকেত আপলোড করুন',
    historyTrends: 'ইতিহাস এবং প্রবণতা',
    screeningReports: 'স্ক্রিনিং রিপোর্ট',
    signalType: 'সংকেত প্রকার নির্বাচন করুন',
    chooseFile: 'সংকেত ফাইল নির্বাচন করুন',
    analyzeNow: 'এখন বিশ্লেষণ করুন',
    signalQuality: 'সংকেত গুণমান স্কোর',
    heartRate: 'হৃদস্পন্দন বিশ্লেষণ',
    aiPrediction: 'AI মডেল পূর্বাভাস',
    downloadPdf: 'পিডিএফ রিপোর্ট ডাউনলোড করুন',
    dateAndTime: 'তারিখ ও সময়',
    filterType: 'ফিল্টার প্রকার',
    sortBy: 'সাজান',
    recentAnalyses: 'সাম্প্রতিক বিশ্লেষণ',
    hospitalMode: 'হাসপাতাল মোড',
    cardiacScreeningUpload: 'হৃদরোগ স্ক্রিনিং এবং রোগী আপলোড',
    doctorClinicalUpload: 'ডাক্তার ক্লিনিকাল আপলোড',
    uploadSubtitle: 'কার্ডিয়াক রেকর্ডিং আপলোড করুন অথবা গবেষণা ডেটাসেট নির্বাচন করুন।',
    voltage: 'ভোল্টেজ',
    ecgDesc: 'ইলেক্ট্রোকার্ডিওগ্রাম বৈদ্যুতিক সংকেত।',
    optical: 'অপটিক্যাল',
    ppgDesc: 'ফোটোপ্লেথিসমোগ্রাম রক্ত স্পন্দন তরঙ্গ।',
    instantTestDatasets: 'তাত্ক্ষণিক পরীক্ষা ডেটাসেট',
    preloadedRecordings: 'প্রি-লোড করা গবেষণা রেকর্ডিং',
    noFilesHint: 'ফাইল নেই? অবিলম্বে পরীক্ষা করতে নিচে ক্লিক করুন:',
    testDatasetsDownload: 'পরীক্ষা ডেটাসেট এবং WFDB ফাইল:',
    clickToDownload: 'পিসিতে ডাউনলোড করতে ক্লিক করুন',
    enterPatientDetails: 'রোগীর বিবরণ প্রদান করুন এবং বিশ্লেষণ করুন',
    standardOverview: 'মানক ওভারভিউ',
    hospitalDeviceLink: 'হাসপাতাল ডিভাইস লিঙ্ক',
    clinicalTrialExporter: 'ক্লিনিকাল ট্রায়াল এক্সপোর্টার',
    dragDropText: 'ECG বা PPG রেকর্ডিং ড্র্যাগ ও ড্রপ করুন',
    orClickBrowse: 'অথবা কম্পিউটার থেকে ব্রাউজ করতে ক্লিক করুন',
    supportedFormats: 'সমর্থিত: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
    clinicalCardiacScreening: 'ক্লিনিকাল কার্ডিয়াক স্ক্রিনিং',
    portalActive: 'পোর্টাল সক্রিয়',
    dashboardSubtitle: '1D-CNN ডিপ লার্নিং দ্বারা রিয়েল-টাইম ECG এবং PPG স্ক্রিনিং।',
    viewHistoryRecords: 'ইতিহাস রেকর্ড দেখুন',
    analyzeCsvHint: 'CSV, TXT, EDF ক্লিনিকাল সিগন্যাল বিশ্লেষণ করুন',
    trackHeartHistory: 'হৃদস্পন্দন ও AI আস্থার ইতিহাস ট্র্যাক করুন',
    doctorPatientPortal: 'ডাক্তার রোগী পোর্টাল',
    reviewPatientCohorts: 'রোগী দল ও নোট পর্যালোচনা করুন',
    downloadPdfReports: 'ফরম্যাট করা PDF রিপোর্ট ডাউনলোড করুন',
    smartSystemAlerts: 'স্মার্ট সিস্টেম সতর্কতা',
    reviewAnalysis: 'বিশ্লেষণ পর্যালোচনা করুন',
    loadingStats: 'স্ক্রিনিং পরিসংখ্যান লোড হচ্ছে...',
    loadingDashboard: 'ড্যাশবোর্ড লোড হচ্ছে...',
    clinicalCapabilities: 'ক্লিনিকাল সক্ষমতা ও AI আর্কিটেকচার',
    clinicalCapabilitiesSubtitle: 'এন্ড-টু-এন্ড ECG বিশ্লেষণ, ব্যাখ্যা মডেল এবং রিপোর্ট রপ্তানি।',
    cnnTitle: '1D-CNN ডিপ লার্নিং',
    cnnDesc: 'স্বয়ংক্রিয় কার্ডিয়াক রিদম শ্রেণীবিভাগের জন্য 3,600-নমুনা উইন্ডোতে CNN।',
    cnnBadge: 'রিয়েল-টাইম অনুমান (<2.0s)',
    xaiTitle: 'ব্যাখ্যাযোগ্য AI (XAI) ওভারলে',
    xaiDesc: 'ডিপ মডেলের পূর্বাভাসকে প্রভাবিত করা সময়কাল হাইলাইট করা হিটম্যাপ।',
    xaiBadge: 'উচ্চ ক্লিনিকাল স্বচ্ছতা',
    pdfTitle: 'বহুভাষিক PDF রপ্তানি',
    pdfDesc: '7টি ভাষায় ক্লিনিকাল PDF রিপোর্ট ডাউনলোড করুন।',
    pdfBadge: 'নেটিভ i18n রেন্ডারার',
    statTotalAnalyses: 'মোট বিশ্লেষণ',
    statCompletedRecordings: 'সম্পন্ন রেকর্ডিং',
    statNormal: 'স্বাভাবিক',
    statNormalSinus: 'স্বাভাবিক সাইনাস ছন্দ',
    statNeedsReview: 'পর্যালোচনা প্রয়োজন',
    statFlaggedLow: 'চিহ্নিত বা কম আস্থা',
    statPoorQuality: 'খারাপ মান',
    statHighNoise: 'উচ্চ শব্দ বা আর্টিফ্যাক্ট',
    latestRecording: 'সর্বশেষ রেকর্ডিং',
    aiRhythmClassification: 'AI রিদম শ্রেণীবিভাগ',
    confidence: 'আস্থা',
    heartRateLabel: 'হৃদস্পন্দন',
    qualityLabel: 'মান',
    anomalyLabel: 'অস্বাভাবিকতা',
    viewFullWaveform: 'সম্পূর্ণ ওয়েভফর্ম ও XAI দেখুন',
    liveScanner: 'লাইভ স্ক্যানার',
    settingsProfile: 'সেটিংস ও প্রোফাইল',
    signingOut: 'সাইন আউট হচ্ছে...',
    screeningRecordsHistory: 'স্ক্রিনিং রেকর্ড ইতিহাস',
  },
  kn: {
    brandName: 'ಕಾರ್ಡಿಯೋಸೆನ್ಸ್ AI',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    newAnalysis: 'ಹೊಸ ವಿಶ್ಲೇಷಣೆ',
    history: 'ಇತಿಹಾಸ',
    doctorPortal: 'ವೈದ್ಯರ ಪೋರ್ಟಲ್',
    adminPanel: 'ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    welcomeBack: 'ಸ್ವಾಗತ',
    patientMode: 'ರೋಗಿ ಮೋಡ್',
    doctorMode: 'ವೈದ್ಯರ ಮೋಡ್',
    adminMode: 'ಅಡ್ಮಿನ್ ಮೋಡ್',
    uploadNewSignal: 'ಹೊಸ ಸಿಗ್ನಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    historyTrends: 'ಇತಿಹಾಸ ಮತ್ತು ಪ್ರವೃತ್ತಿಗಳು',
    screeningReports: 'ಸ್ಕ್ರೀನಿಂಗ್ ವರದಿಗಳು',
    signalType: 'ಸಿಗ್ನಲ್ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    chooseFile: 'ಸಿಗ್ನಲ್ ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    analyzeNow: 'ಈಗ ವಿಶ್ಲೇಷಿಸಿ',
    signalQuality: 'ಸಿಗ್ನಲ್ ಗುಣಮಟ್ಟದ ಸ್ಕೋರ್',
    heartRate: 'ಹೃದಯ ಬಡಿತ ವಿಶ್ಲೇಷಣೆ',
    aiPrediction: 'AI ಮಾಡೆಲ್ ಮುನ್ನೋಟ',
    downloadPdf: 'PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    dateAndTime: 'ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
    filterType: 'ಫಿಲ್ಟರ್ ಪ್ರಕಾರ',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    recentAnalyses: 'ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಗಳು',
    hospitalMode: 'ಆಸ್ಪತ್ರೆ ಮೋಡ್',
    cardiacScreeningUpload: 'ಹೃದಯ ತಪಾಸಣೆ ಮತ್ತು ರೋಗಿ ಅಪ್‌ಲೋಡ್',
    doctorClinicalUpload: 'ವೈದ್ಯಕೀಯ ಕ್ಲಿನಿಕಲ್ ಅಪ್‌ಲೋಡ್',
    uploadSubtitle: 'ಕಾರ್ಡಿಯಾಕ್ ರೆಕಾರ್ಡಿಂಗ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ లేదా ರಿಸರ್ಚ್ ಡೇಟಾಸೆಟ್ ಆಯ್ಕೆಮಾಡಿ.',
    voltage: 'ವೋಲ್ಟೇಜ್',
    ecgDesc: 'ಎಲೆಕ್ಟ್ರೋಕಾರ್ಡಿಯೋಗ್ರಾಮ್ ಸಿಗ್ನಲ್ ಲೀಡ್స్.',
    optical: 'ಆಪ್ಟಿಕಲ್',
    ppgDesc: 'ಫೋಟೋಪ್ಲೆಥಿಸ್ಮೋಗ್ರಾಮ್ ರಕ್ತದ ಬಡಿತ ಅಲೆಗಳು.',
    instantTestDatasets: 'ತ್ವರಿತ ಪರೀಕ್ಷಾ ಡೇಟಾಸೆಟ್‌ಗಳು',
    preloadedRecordings: 'ಪೂರ್ವ-ಲೋಡ್ ಮಾಡಲಾದ ರಿಸರ್ಚ್ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳು',
    noFilesHint: 'ಫೈಲ್‌ಗಳಿಲ್ಲವೇ? ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಪರೀಕ್ಷಿಸಲು ಕೆಳಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ:',
    testDatasetsDownload: 'ಪರೀಕ್ಷಾ ಡೇಟಾಸೆಟ್‌ಗಳು ಮತ್ತು WFDB ಫೈಲ್‌ಗಳು:',
    clickToDownload: 'PC ಗೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    enterPatientDetails: 'ರೋಗಿಯ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ',
    standardOverview: 'ಸ್ಟ್ಯಾಂಡರ್ಡ್ ಅವಲೋಕನ',
    hospitalDeviceLink: 'ಆಸ್ಪತ್ರೆ ಸಾಧನದ ಲಿಂಕ್',
    clinicalTrialExporter: 'ಕ್ಲಿನಿಕಲ್ ಟ್ರಯಲ್ ಎಕ್ಸ್‌ಪೋರ್ಟರ್',
    dragDropText: 'ECG ಅಥವಾ PPG ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ಡ್ರಾಗ್ ಮತ್ತು ಡ್ರಾಪ್ ಮಾಡಿ',
    orClickBrowse: 'ಅಥವಾ ನಿಮ್ಮ ಕಂಪ್ಯೂಟರ್‌ನಿಂದ ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    supportedFormats: 'ಬೆಂಬಲಿತವಾಗಿದೆ: .CSV, .TXT, .EDF, .DAT, .HEA, .ATR',
    clinicalCardiacScreening: 'ಕ್ಲಿನಿಕಲ್ ಕಾರ್ಡಿಯಾಕ್ ಸ್ಕ್ರೀನಿಂಗ್',
    portalActive: 'ಪೋರ್ಟಲ್ ಸಕ್ರಿಯ',
    dashboardSubtitle: '1D-CNN ಡೀಪ್ ಲರ್ನಿಂಗ್ ಮೂಲಕ ರಿಯಲ್-ಟೈಮ್ ECG ಮತ್ತು PPG ಸ್ಕ್ರೀನಿಂಗ್.',
    viewHistoryRecords: 'ಇತಿಹಾಸ ದಾಖಲೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    analyzeCsvHint: 'CSV, TXT, EDF ಕ್ಲಿನಿಕಲ್ ಸಿಗ್ನಲ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    trackHeartHistory: 'ಹೃದಯ ಬಡಿತ ಮತ್ತು AI ವಿಶ್ವಾಸ ಇತಿಹಾಸ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    doctorPatientPortal: 'ವೈದ್ಯರ ರೋಗಿ ಪೋರ್ಟಲ್',
    reviewPatientCohorts: 'ರೋಗಿ ಗುಂಪುಗಳು ಮತ್ತು ಟಿಪ್ಪಣಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    downloadPdfReports: 'ಫಾರ್ಮ್ಯಾಟ್ ಮಾಡಿದ PDF ವರದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    smartSystemAlerts: 'ಸ್ಮಾರ್ಟ್ ಸಿಸ್ಟಮ್ ಎಚ್ಚರಿಕೆಗಳು',
    reviewAnalysis: 'ವಿಶ್ಲೇಷಣೆ ಪರಿಶೀಲಿಸಿ',
    loadingStats: 'ಸ್ಕ್ರೀನಿಂಗ್ ಅಂಕಿಅಂಶಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    loadingDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    clinicalCapabilities: 'ಕ್ಲಿನಿಕಲ್ ಸಾಮರ್ಥ್ಯಗಳು ಮತ್ತು AI ಆರ್ಕಿಟೆಕ್ಚರ್',
    clinicalCapabilitiesSubtitle: 'ಎಂಡ್-ಟು-ಎಂಡ್ ECG ವಿಶ್ಲೇಷಣೆ, ವಿವರಣೆ ಮಾದರಿಗಳು ಮತ್ತು ವರದಿ ರಫ್ತು.',
    cnnTitle: '1D-CNN ಡೀಪ್ ಲರ್ನಿಂಗ್',
    cnnDesc: 'ಸ್ವಯಂಚಾಲಿತ ಕಾರ್ಡಿಯಾಕ್ ರಿದಮ್ ವರ್ಗೀಕರಣಕ್ಕಾಗಿ 3,600-ನಮೂನೆ ವಿಂಡೋಗಳಲ್ಲಿ CNN.',
    cnnBadge: 'ರಿಯಲ್-ಟೈಮ್ ಅನುಮಾನ (<2.0s)',
    xaiTitle: 'ವಿವರಣಾತ್ಮಕ AI (XAI) ಓವರ್ಲೇ',
    xaiDesc: 'ಡೀಪ್ ಮಾದರಿ ಮುನ್ಸೂಚನೆಯನ್ನು ಪ್ರಭಾವಿಸಿದ ಕಾಲಾವಧಿ ಪ್ರದೇಶಗಳನ್ನು ಹೈಲೈಟ್ ಮಾಡುವ ಹೀಟ್‌ಮ್ಯಾಪ್‌ಗಳು.',
    xaiBadge: 'ಉನ್ನತ ಕ್ಲಿನಿಕಲ್ ಪಾರದರ್ಶಕತೆ',
    pdfTitle: 'ಬಹುಭಾಷಾ PDF ರಫ್ತು',
    pdfDesc: '7 ಭಾಷೆಗಳಲ್ಲಿ ಕ್ಲಿನಿಕಲ್ PDF ವರದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    pdfBadge: 'ನೇಟಿವ್ i18n ರೆಂಡರರ್',
    statTotalAnalyses: 'ಒಟ್ಟು ವಿಶ್ಲೇಷಣೆಗಳು',
    statCompletedRecordings: 'ಪೂರ್ಣಗೊಂಡ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳು',
    statNormal: 'ಸಾಮಾನ್ಯ',
    statNormalSinus: 'ಸಾಮಾನ್ಯ ಸೈನಸ್ ರಿದಮ್',
    statNeedsReview: 'ಪರಿಶೀಲನೆ ಅಗತ್ಯ',
    statFlaggedLow: 'ಫ್ಲ್ಯಾಗ್ ಅಥವಾ ಕಡಿಮೆ ವಿಶ್ವಾಸ',
    statPoorQuality: 'ಕಳಪೆ ಗುಣಮಟ್ಟ',
    statHighNoise: 'ಹೆಚ್ಚಿನ ಶಬ್ದ ಅಥವಾ ಆರ್ಟಿಫ್ಯಾಕ್ಟ್',
    latestRecording: 'ಇತ್ತೀಚಿನ ರೆಕಾರ್ಡಿಂಗ್',
    aiRhythmClassification: 'AI ರಿದಮ್ ವರ್ಗೀಕರಣ',
    confidence: 'ವಿಶ್ವಾಸ',
    heartRateLabel: 'ಹೃದಯ ಬಡಿತ',
    qualityLabel: 'ಗುಣಮಟ್ಟ',
    anomalyLabel: 'ವೈಪರೀತ್ಯ',
    viewFullWaveform: 'ಪೂರ್ಣ ವೇವ್‌ಫಾರ್ಮ್ ಮತ್ತು XAI ವೀಕ್ಷಿಸಿ',
    liveScanner: 'ಲೈವ್ ಸ್ಕ್ಯಾನರ್',
    settingsProfile: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಪ್ರೊಫೈಲ್',
    signingOut: 'ಸೈನ್ ಔಟ್ ಆಗುತ್ತಿದೆ...',
    screeningRecordsHistory: 'ಸ್ಕ್ರೀನಿಂಗ್ ದಾಖಲೆ ಇತಿಹಾಸ',
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('cardiosense_lang') as Language
    if (saved && LANGUAGES.some((l) => l.code === saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('cardiosense_lang', lang)
  }

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en
    return dict[key] || TRANSLATIONS.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
