import React from 'react'
import Link from 'next/link'
import { FileText, ArrowLeft, AlertTriangle, ShieldCheck, Scale, CheckCircle2 } from 'lucide-react'

export default function TermsOfServicePage() {
  return (
    <div className="container-main max-w-4xl py-10 space-y-8">
      {/* Navigation link */}
      <Link
        href="/dashboard"
        className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-blue-600 transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Dashboard
      </Link>

      {/* Header */}
      <div className="card p-8 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 text-white border-0 shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 -mt-10 -mr-10 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex items-center gap-3 mb-3">
          <span className="p-2.5 bg-amber-500/20 text-amber-300 rounded-xl border border-amber-500/30">
            <Scale className="w-6 h-6" />
          </span>
          <span className="text-xs font-bold uppercase tracking-wider text-amber-300">
            Terms & Conditions
          </span>
        </div>

        <h1 className="text-3xl font-black tracking-tight text-white mb-2">
          Terms of Service
        </h1>
        <p className="text-slate-300 text-sm max-w-2xl leading-relaxed">
          Terms governing the use of Cardiosense AI research, screening prototype tools, and clinical dashboards.
        </p>
        <p className="text-xs text-slate-400 mt-4">
          Last Updated: August 2026 | Effective for Version 1.0 Platform
        </p>
      </div>

      {/* Main Content Sections */}
      <div className="card p-8 bg-white space-y-8 text-slate-700 text-sm leading-relaxed border border-slate-200">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <FileText className="w-5 h-5 text-amber-600" /> 1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using the <strong>Cardiosense AI</strong> platform, web application, or API endpoints, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the application.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <AlertTriangle className="w-5 h-5 text-amber-600" /> 2. Research Prototype & Non-Diagnostic Disclaimer
          </h2>
          <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl space-y-2 text-xs font-medium text-amber-950">
            <p>⚠️ <strong>Research & Screening Tool:</strong> Cardiosense AI is an artificial intelligence screening prototype developed for research, education, and technical evaluation.</p>
            <p>⚠️ <strong>Not a Medical Diagnosis:</strong> Deep learning predictions, heart rate estimates, signal quality scores, and PDF reports generated by this application <strong>do not constitute formal medical diagnoses</strong> or definitive clinical evaluations.</p>
            <p>⚠️ <strong>Emergency Situations:</strong> If you are experiencing chest pain, shortness of breath, or cardiac distress, seek immediate medical attention or call emergency services immediately.</p>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <CheckCircle2 className="w-5 h-5 text-amber-600" /> 3. Acceptable Use
          </h2>
          <p>You agree to use Cardiosense AI solely for lawful screening and evaluation purposes. You must not:</p>
          <ul className="list-disc pl-5 space-y-1 text-xs">
            <li>Attempt to reverse engineer or extract raw proprietary model weights without permission.</li>
            <li>Submit malicious files or attempt to disrupt system API servers.</li>
            <li>Misrepresent AI-generated screening scores as certified physician diagnoses to third parties.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <ShieldCheck className="w-5 h-5 text-amber-600" /> 4. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, the Cardiosense AI team shall not be liable for any indirect, incidental, or consequential damages resulting from the use or inability to use the screening software.
          </p>
        </section>

        <section className="pt-4 border-t border-slate-200 text-xs text-slate-500">
          <p>For questions regarding these Terms, contact <a href="mailto:terms@cardiosense.ai" className="text-blue-600 underline">terms@cardiosense.ai</a> or view the source repository at <a href="https://github.com/Tusharjain-19/cardiosense_ai" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline">GitHub</a>.</p>
        </section>
      </div>
    </div>
  )
}
