import { Analysis, User } from '@/types'
import jsPDF from 'jspdf'

export type ReportLanguage = 'en' | 'hi' | 'ta' | 'te' | 'gu' | 'mr' | 'bn' | 'kn'

export const PDF_TRANSLATIONS: Record<ReportLanguage, Record<string, string>> = {
  en: {
    reportTitle: 'CARDIOSENSE AI',
    subTitle: 'CLINICAL CARDIAC SIGNAL SCREENING & EXPLAINABILITY REPORT',
    patientSection: '1. Patient & Recording Metadata',
    patientName: 'Patient Name:',
    ageGender: 'Age / Gender:',
    fileName: 'Recording File:',
    fileType: 'Signal Type:',
    processedAt: 'Report Date:',
    metricsSection: '2. Quantitative Cardiac Vitals & Electrophysiological Metrics',
    qualityScore: 'Signal Quality Score:',
    noiseLevel: 'Artifact Noise Level:',
    baselineStability: 'Baseline Wander:',
    heartRateAvg: 'Average Heart Rate:',
    hrRange: 'Min / Max Heart Rate:',
    hrVariability: 'Heart Rate Variability:',
    prInterval: 'Estimated PR Interval:',
    qrsDuration: 'Estimated QRS Duration:',
    qtcInterval: 'Estimated QTc Interval:',
    aiSection: '3. Deep Learning Classification & AI Confidence',
    classificationLabel: 'AI PRIMARY CLASSIFICATION:',
    confidenceLabel: 'AI Model Confidence Score:',
    probabilityTitle: 'Class Probability Distribution Breakdown:',
    graphSection: '4. Diagnostic Signal Waveform Graph (Standard ECG Grid Paper)',
    explainableSection: '5. AI Model Saliency & Normal Baseline Comparison Graph',
    focusSegment: 'Attention Timeframe:',
    focusDescription: 'Model Observation:',
    riskSection: '6. Risk Stratification & Clinical Triage Assessment',
    riskLevel: 'Clinical Risk Level:',
    doctorSection: '7. Healthcare Professional Clinical Validation',
    reviewedBy: 'Reviewing Physician:',
    clinicalAssessment: 'Clinical Assessment:',
    clinicalNotes: 'Physician Notes:',
    recommendationsSection: '8. Point-Wise Clinical Action Plan & Recommendations (What To Do)',
    recNormalItem1: '1. Routine Cardiovascular Screening: Continue scheduled annual cardiovascular health checkups.',
    recNormalItem2: '2. Balanced Hydration & Diet: Maintain 2.5L daily hydration, low-sodium nutrition, and stress management.',
    recNormalItem3: '3. Regular Aerobic Exercise: Engage in 150 minutes of moderate aerobic activity weekly.',
    recNormalItem4: '4. Resting Heart Rate Tracking: Log your resting heart rate once weekly using wearable or manual check.',
    recNormalItem5: '5. Primary Care Discussion: Review these baseline screening results during your next routine physical.',
    recNormalItem6: '6. Lifestyle Modification: Avoid tobacco products and limit excessive caffeine or alcohol intake.',
    recNormalItem7: '7. Digital Record Retention: Store this PDF report in your personal electronic health folder.',
    recAbnormalItem1: '1. Urgent Specialist Evaluation: Schedule a clinical evaluation with a certified cardiologist for a 12-lead ECG.',
    recAbnormalItem2: '2. Symptom Event Journal: Record any episodes of dizziness, chest tightness, palpitations, or dyspnea.',
    recAbnormalItem3: '3. Emergency Red-Flag Protocol: Seek immediate ER care if experiencing acute chest pain, pressure, or syncope.',
    recAbnormalItem4: '4. Daily Vitals Monitoring: Measure and record resting heart rate and blood pressure twice daily (morning & evening).',
    recAbnormalItem5: '5. Medication Safety Review: Bring all current prescriptions to your doctor to evaluate QT-prolonging drugs.',
    recAbnormalItem6: '6. Activity Restriction: Avoid strenuous physical exertion until cleared by your treating physician.',
    recAbnormalItem7: '7. Clinical Data Sharing: Share this full PDF report and raw waveform file with your cardiology team.',
    disclaimerTitle: 'IMPORTANT CLINICAL DISCLAIMER',
    disclaimerBody: 'This report is generated by Cardiosense AI for research and screening demonstration. It does not replace a formal clinical diagnosis by a licensed physician or cardiologist.',
  },
  hi: {
    reportTitle: 'कार्डियोसेंस एआई',
    subTitle: 'क्लिनिकल कार्डिएक वेवफॉर्म स्क्रीनिंग रिपोर्ट',
    patientSection: '1. रोगी एवं रिकॉर्डिंग जानकारी',
    patientName: 'रोगी का नाम:',
    ageGender: 'आयु / लिंग:',
    fileName: 'रिकॉर्डिंग फ़ाइल:',
    fileType: 'सिग्नल प्रकार:',
    processedAt: 'रिपोर्ट दिनांक:',
    metricsSection: '2. मात्रात्मक कार्डिएक पैरामीटर एवं मैट्रिक्स',
    qualityScore: 'सिग्नल गुणवत्ता स्कोर:',
    noiseLevel: 'शोर स्तर:',
    baselineStability: 'बेसलाइन स्थिरता:',
    heartRateAvg: 'औसत हृदय गति:',
    hrRange: 'न्यूनतम / अधिकतम हृदय गति:',
    hrVariability: 'हृदय गति परिवर्तनशीलता:',
    prInterval: 'अनुमानित PR अंतराल:',
    qrsDuration: 'अनुमानित QRS अवधि:',
    qtcInterval: 'अनुमानित QTc अंतराल:',
    aiSection: '3. एआई डीप लर्निंग वर्गीकरण परिणाम',
    classificationLabel: 'एआई प्राथमिक वर्गीकरण:',
    confidenceLabel: 'मॉडल का विश्वास स्कोर:',
    probabilityTitle: 'वर्ग संभावना वितरण:',
    graphSection: '4. नैदानिक वेवफॉर्म ग्राफ़ (ईसीजी ग्रिड पेपर)',
    explainableSection: '5. एआई मॉडल तुलना एवं एक्सएआई (XAI) ग्राफ़',
    focusSegment: 'ध्यान क्षेत्र समय सीमा:',
    focusDescription: 'मॉडल अवलोकन:',
    riskSection: '6. जोखिम वर्गीकरण एवं क्लिनिकल ट्राइएज मूल्यांकन',
    riskLevel: 'क्लिनिकल जोखिम स्तर:',
    doctorSection: '7. चिकित्सक क्लिनिकल सत्यापन एवं समीक्षा',
    reviewedBy: 'समीक्षाकर्ता चिकित्सक:',
    clinicalAssessment: 'क्लिनिकल मूल्यांकन:',
    clinicalNotes: 'चिकित्सक नोट्स:',
    recommendationsSection: '8. बिंदुवार क्लिनिकल कार्य योजना एवं अनुशंसाएं (क्या करें)',
    recNormalItem1: '1. नियमित स्वास्थ्य जांच: नियमित वार्षिक हृदय स्वास्थ्य जांच जारी रखें।',
    recNormalItem2: '2. जीवन शैली प्रबंधन: संतुलित आहार, पर्याप्त जल, नियमित व्यायाम और तनाव प्रबंधन बनाए रखें।',
    recNormalItem3: '3. एरोबिक व्यायाम: प्रति सप्ताह 150 मिनट मध्यम एरोबिक गतिविधि करें।',
    recNormalItem4: '4. हृदय गति ट्रैकिंग: सप्ताह में एक बार अपनी विश्राम हृदय गति नोट करें।',
    recNormalItem5: '5. डॉक्टर परामर्श: अपनी अगली नियमित जांच के दौरान डॉक्टर से इन परिणामों पर चर्चा करें।',
    recNormalItem6: '6. जीवनशैली में सुधार: तंबाकू का सेवन न करें और कैफीन या शराब का सीमित सेवन करें।',
    recNormalItem7: '7. डिजिटल रिकॉर्ड सहेजें: यह पीडीएफ रिपोर्ट अपने व्यक्तिगत स्वास्थ्य फ़ोल्डर में सुरक्षित रखें।',
    recAbnormalItem1: '1. कार्डियोलॉजिस्ट परामर्श: 12-लीड ईसीजी परीक्षण के लिए योग्य हृदय रोग विशेषज्ञ से परामर्श लें।',
    recAbnormalItem2: '2. लक्षण ट्रैकिंग: चक्कर आना, घबराहट या सांस फूलने जैसे लक्षणों पर ध्यान दें और नोट करें।',
    recAbnormalItem3: '3. आपातकालीन चेतावनी: सीने में तेज दर्द या सांस लेने में असमर्थता होने पर तुरंत आपातकालीन चिकित्सा सहायता लें।',
    recAbnormalItem4: '4. दैनिक वाइटल्स ट्रैकिंग: सुबह और शाम अपनी हृदय गति और रक्तचाप मापें और रिकॉर्ड करें।',
    recAbnormalItem5: '5. दवा सुरक्षा समीक्षा: क्यूटी-प्रोलॉन्गिंग दवाओं के मूल्यांकन के लिए अपनी दवा सूची डॉक्टर को दिखाएं।',
    recAbnormalItem6: '6. शारीरिक गतिविधि प्रतिबंध: डॉक्टर की अनुमति मिलने तक भारी शारीरिक श्रम से बचें।',
    recAbnormalItem7: '7. रिपोर्ट शेयरिंग: यह स्क्रीनिंग रिपोर्ट और वेवफॉर्म फ़ाइल अपने कार्डियोलॉजिस्ट के साथ साझा करें।',
    disclaimerTitle: 'महत्वपूर्ण चिकित्सा अस्वीकरण',
    disclaimerBody: 'यह रिपोर्ट कार्डियोसेंस एआई द्वारा स्क्रीनिंग के उद्देश्यों के लिए बनाई गई है। यह औपचारिक चिकित्सा निदान नहीं है।',
  },
  ta: {
    reportTitle: 'கார்டியோசென்ஸ் AI',
    subTitle: 'மருத்துவ இதய அலைவடிவ பரிசோதனை அறிக்கை',
    patientSection: '1. நோயாளி மற்றும் பதிவுத் தகவல்',
    patientName: 'நோயாளி பெயர்:',
    ageGender: 'வயது / பாலினம்:',
    fileName: 'பதிவுக் கோப்பு:',
    fileType: 'சமிக்ஞை வகை:',
    processedAt: 'அறிக்கை தேதி:',
    metricsSection: '2. இதய துடிப்பு மற்றும் அலைவடிவ அளவீடுகள்',
    qualityScore: 'சமிக்ஞை தர மதிப்பீடு:',
    noiseLevel: 'இரைச்சல் நிலை:',
    baselineStability: 'அடிப்படை நிலைத்தன்மை:',
    heartRateAvg: 'சராசரி இதய துடிப்பு:',
    hrRange: 'குறைந்தபட்ச / அதிகபட்ச துடிப்பு:',
    hrVariability: 'இதய துடிப்பு மாறுபாடு:',
    prInterval: 'மதிப்பிடப்பட்ட PR இடைவெளி:',
    qrsDuration: 'மதிப்பிடப்பட்ட QRS காலம்:',
    qtcInterval: 'மதிப்பிடப்பட்ட QTc இடைவெளி:',
    aiSection: '3. AI ஆழமான கற்றல் வகைப்பாடு முடிவு',
    classificationLabel: 'AI முதன்மை வகைப்பாடு:',
    confidenceLabel: 'மாடல் நம்பிக்கை மதிப்பெண்:',
    probabilityTitle: 'வகை நிகழ்தகவு பங்கீடு:',
    graphSection: '4. அலைவடிவ காட்சிப்படுத்தல் (ECG வரைபடக் தாள்)',
    explainableSection: '5. AI மாதிரி ஒப்பீடு & XAI வரைபடம்',
    focusSegment: 'கவனப் பகுதி நேரம்:',
    focusDescription: 'மாடல் அவதானிப்பு:',
    riskSection: '6. மருத்துவ ஆபத்து மதிப்பீடு',
    riskLevel: 'மருத்துவ ஆபத்து நிலை:',
    doctorSection: '7. மருத்துவர் மருத்துவ சரிபார்ப்பு',
    reviewedBy: 'மதிப்பாய்வு செய்த மருத்துவர்:',
    clinicalAssessment: 'மருத்துவ மதிப்பீடு:',
    clinicalNotes: 'மருத்துவர் குறிப்புகள்:',
    recommendationsSection: '8. மருத்துவப் பரிந்துரைகள் & செயல் திட்டம் (என்ன செய்ய வேண்டும்)',
    recNormalItem1: '1. வழக்கமான கண்காணிப்பு: வழக்கமான ஆண்டு சுகாதாரப் பரிசோதனைகளைத் தொடரவும்.',
    recNormalItem2: '2. ஆரோக்கியமான பழக்கங்கள்: சீரான உணவு, போதுமான நீர் மற்றும் உடற்பயிற்சியைப் பேணவும்.',
    recNormalItem3: '3. உடற்பயிற்சி: வாரத்திற்கு 150 நிமிடங்கள் மிதமான உடற்பயிற்சி செய்யவும்.',
    recNormalItem4: '4. இதய துடிப்பு பதிவு: வாரத்திற்கு ஒரு முறை ஓய்வுநேர இதய துடிப்பைப் பதிவு செய்யவும்.',
    recNormalItem5: '5. மருத்துவர் ஆலோசனை: அடுத்த சந்திப்பில் இதய ஆரோக்கியம் பற்றி விவாதிக்கவும்.',
    recNormalItem6: '6. புகையிலை தவிர்த்தல்: புகையிலை மற்றும் அதிக காஃபின் உட்கொள்வதைத் தவிர்க்கவும்.',
    recNormalItem7: '7. மின்னணு பதிவு: இந்த PDF அறிக்கையை உங்கள் தனிப்பட்ட சுகாதாரக் கோப்பில் சேமிக்கவும்.',
    recAbnormalItem1: '1. நிபுணர் ஆலோசனை: விரிவான பரிசோதனைக்கு இருதயவியல் நிபுணரை அணுகவும்.',
    recAbnormalItem2: '2. அறிகுறி கண்காணிப்பு: தலைச்சுற்றல், நெஞ்சடைப்பு அல்லது மூச்சுத்திணறலை கவனிக்கவும்.',
    recAbnormalItem3: '3. அவசர எச்சரிக்கை: கடுமையான நெஞ்சு வலி ஏற்பட்டால் உடனடியாக அவசர உதவியை நாடவும்.',
    recAbnormalItem4: '4. தினசரி இரத்த அழுத்தப் பதிவு: காலை மற்றும் மாலையில் இதய துடிப்பு மற்றும் இரத்த அழுத்தத்தைப் பதிவு செய்யவும்.',
    recAbnormalItem5: '5. மருந்து ஆய்வு: நீங்கள் உட்கொள்ளும் மருந்துகளின் பட்டியலை மருத்துவரிடம் காண்பிக்கவும்.',
    recAbnormalItem6: '6. தீவிர உடற்பயிற்சி கட்டுப்பாடு: மருத்துவரின் அனுமதி கிடைக்கும் வரை கடினமான உடற்பயிற்சிகளைத் தவிர்க்கவும்.',
    recAbnormalItem7: '7. அறிக்கை பகிர்தல்: இந்த அறிக்கையை உங்கள் இருதய மருத்துவரிடம் சமர்ப்பிக்கவும்.',
    disclaimerTitle: 'முக்கியமான மருத்துவ மறுப்பு',
    disclaimerBody: 'இந்த அறிக்கை பரிசோதனை நோக்கங்களுக்காக மட்டுமே உருவாக்கப்பட்டது. இது மருத்துவ நோயறிதல் அல்ல.',
  },
  te: {
    reportTitle: 'కార్డియోసెన్స్ AI',
    subTitle: 'క్లినికల్ కార్డియాక్ వేవ్‌ఫార్మ్ నివేదిక',
    patientSection: '1. రోగి మరియు రికార్డింగ్ సమాచారం',
    patientName: 'రోగి పేరు:',
    ageGender: 'వయస్సు / లింగం:',
    fileName: 'రికార్డింగ్ ఫైల్:',
    fileType: 'సిగ్నల్ రకం:',
    processedAt: 'నివేదిక తేదీ:',
    metricsSection: '2. గుండె వేగం & వేవ్‌ఫార్మ్ పారామితులు',
    qualityScore: 'సిగ్నల్ క్వాలిటీ స్కోర్:',
    noiseLevel: 'నాయిస్ స్థాయి:',
    baselineStability: 'బేస్‌లైన్ స్థిరత్వం:',
    heartRateAvg: 'సగటు గుండె వేగం:',
    hrRange: 'కనిష్ట / గరిష్ట గుండె వేగం:',
    hrVariability: 'గుండె వేగం వైవిధ్యం:',
    prInterval: 'అంచనా వేసిన PR వ్యవధి:',
    qrsDuration: 'అంచనా వేసిన QRS సమయం:',
    qtcInterval: 'అంచనా వేసిన QTc వ్యవధి:',
    aiSection: '3. AI డీప్ లెర్నింగ్ వర్గీకరణ ఫలితం',
    classificationLabel: 'AI ప్రాథమిక వర్గీకరణ:',
    confidenceLabel: 'మోడల్ విశ్వాస స్కోర్:',
    probabilityTitle: 'సంభావ్యత పంపిణీ:',
    graphSection: '4. వేవ్‌ఫార్మ్ గ్రాఫ్ (ECG గ్రిడ్ పేపర్)',
    explainableSection: '5. AI మోడల్ పోలిక & XAI గ్రాఫ్',
    focusSegment: 'ఫోకస్ సమయ వ్యవధి:',
    focusDescription: 'మోడల్ పరిశీలన:',
    riskSection: '6. క్లినికల్ రిస్క్ అంచనా',
    riskLevel: 'రిస్క్ స్థాయి:',
    doctorSection: '7. వైద్యుల క్లినికల్ తనిఖీ మరియు సమీక్ష',
    reviewedBy: 'సమీక్షించిన డాక్టర్:',
    clinicalAssessment: 'క్లినికల్ అంచనా:',
    clinicalNotes: 'డాక్టర్ గమనికలు:',
    recommendationsSection: '8. క్లినికల్ సిఫార్సులు & కార్యాచరణ ప్రణాళిక (ఏం చేయాలి)',
    recNormalItem1: '1. సాధారణ పర్యవేక్షణ: క్రమమైన వార్షిక ఆరోగ్య పరీక్షలను కొనసాగించండి.',
    recNormalItem2: '2. జీవనశైలి నిర్వహణ: సమతుల్య ఆహారం మరియు క్రమమైన వ్యాయామం పాటించండి.',
    recNormalItem3: '3. ఏరోబిక్ వ్యాయామం: వారానికి 150 నిమిషాల మోస్తరు వ్యాయామం చేయండి.',
    recNormalItem4: '4. హృదయ స్పందనల నమోదు: వారానికి ఒకసారి విశ్రాంతి సమయ గుండె వేగాన్ని గమనించండి.',
    recNormalItem5: '5. డాక్టర్ సలహా: తదుపరి వైద్య పరీక్షలో గుండె ఆరోగ్యం గురించి చర్చించండి.',
    recNormalItem6: '6. ఆరోగ్యకరమైన అలవాట్లు: పొగాకు ఉత్పత్తులు మరియు అధిక కెఫిన్ తీసుకోకండి.',
    recNormalItem7: '7. డిజిటల్ రికార్డ్: ఈ PDF నివేదికను మీ వ్యక్తిగత హెల్త్ ఫోల్డర్‌లో భద్రపరచండి.',
    recAbnormalItem1: '1. నిపుణుల సంప్రదింపులు: 12-లీడ్ ECG పరీక్ష కోసం కార్డియాలజిస్ట్‌ను సంప్రదించండి.',
    recAbnormalItem2: '2. లక్షణాల నమోదు: కళ్ళు తిరగడం, గుండె వేగంగా కొట్టుకోవడం గమనించండి.',
    recAbnormalItem3: '3. అత్యవసర హెచ్చరిక: తీవ్రమైన ఛాతీ నెప్పి వస్తే వెంటనే అత్యవసర సహాయం పొందండి.',
    recAbnormalItem4: '4. రోజువారీ రక్తపోటు తనిఖీ: ఉదయం మరియు సాయంత్రం గుండె వేగం మరియు బిపి నమోదు చేయండి.',
    recAbnormalItem5: '5. ఔషధ సమీక్ష: మీ ప్రస్తుత మందుల జాబితాను డాక్టర్‌కు చూపించి సలహా తీసుకోండి.',
    recAbnormalItem6: '6. శారీరక శ్రమ నియంత్రణ: డాక్టర్ అనుమతించే వరకు తీవ్రమైన శారీరక శ్రమకు దూరంగా ఉండండి.',
    recAbnormalItem7: '7. నివేదిక భాగస్వామ్యం: ఈ స్క్రీనింగ్ నివేదికను మీ డాక్టర్‌తో పంచుకోండి.',
    disclaimerTitle: 'ముఖ్యమైన వైద్య నిరాకరణ',
    disclaimerBody: 'ఈ నివేదిక స్క్రీనింగ్ ప్రయోజనాల కోసం మాత్రమే రూపొందించబడింది. ఇది అధికారిక వైద్య నిర్ధారణ కావు.',
  },
  gu: {
    reportTitle: 'કાર્ડિઓસેન્સ AI',
    subTitle: 'ક્લિનિકલ કાર્ડિયાક વેવફોર્મ રિપોર્ટ',
    patientSection: '1. દર્દી અને રેકોર્ડિંગ માહિતી',
    patientName: 'દર્દીનું નામ:',
    ageGender: 'ઉંમર / લિંગ:',
    fileName: 'રેકોર્ડિંગ ફાઇલ:',
    fileType: 'સિગ્નલ પ્રકાર:',
    processedAt: 'રિપોર્ટ તારીખ:',
    metricsSection: '2. હૃદય દર અને વેવફોર્મ પેરામીટર્સ',
    qualityScore: 'સિગ્નલ ગુણવત્તા સ્કોર:',
    noiseLevel: 'નોઇસ સ્તર:',
    baselineStability: 'બેઝલાઇન સ્થિરતા:',
    heartRateAvg: 'સરેરાશ હૃદય દર:',
    hrRange: 'ન્યૂનતમ / મહત્તમ હૃદય દર:',
    hrVariability: 'હૃદય દર પરિવર્તનશીલતા:',
    prInterval: 'અંદાજિત PR સમયગાળો:',
    qrsDuration: 'અંદાજિત QRS સમયગાળો:',
    qtcInterval: 'અંદાજિત QTc સમયગાળો:',
    aiSection: '3. AI ડીપ લર્નિંગ વર્ગીકરણ પરિણામ',
    classificationLabel: 'AI પ્રાથમિક વર્ગીકરણ:',
    confidenceLabel: 'મોડેલ આત્મવિશ્વાસ સ્કોર:',
    probabilityTitle: 'વર્ગ સંભાવના વિતરણ:',
    graphSection: '4. વેવફોર્મ ગ્રાફ (ECG ગ્રીડ પેપર)',
    explainableSection: '5. AI મોડેલ સરખામણી અને XAI ગ્રાફ',
    focusSegment: 'ધ્યાન ક્ષેત્ર સમયગાળો:',
    focusDescription: 'મોડેલ અવલોકન:',
    riskSection: '6. ક્લિનિકલ જોખમ મૂલ્યાંકન',
    riskLevel: 'જોખમ સ્તર:',
    doctorSection: '7. તબીબ ક્લિનિકલ માન્યતા અને સમીક્ષા',
    reviewedBy: 'સમીક્ષા કરનાર તબીબ:',
    clinicalAssessment: 'ક્લિનિકલ મૂલ્યાંકન:',
    clinicalNotes: 'તબીબ નોંધો:',
    recommendationsSection: '8. ક્લિનિકલ ભલામણો અને કાર્ય યોજના (શું કરવું)',
    recNormalItem1: '1. નિયમિત દેખરેખ: નિયમિત વાર્ષિક આરોગ્ય તપાસ ચાલુ રાખો.',
    recNormalItem2: '2. સ્વસ્થ આદતો: સંતુલિત આહાર, પૂરતું પાણી અને નિયમિત વ્યાયામ જાળવો.',
    recNormalItem3: '3. કસરત: અઠવાડિયામાં 150 મિનિટ મધ્યમ એરોબિક કસરત કરો.',
    recNormalItem4: '4. હૃદય દર ટ્રેકિંગ: અઠવાડિયામાં એકવાર આરામના સમયનો હૃદય દર નોંધો.',
    recNormalItem5: '5. તબીબ સલાહ: તમારી આગામી તપાસ દરમિયાન તબીબ સાથે ચર્ચા કરો.',
    recNormalItem6: '6. જીવનશૈલી ફેરફાર: તમાકુ અને વધુ પડતા કેફીનથી દૂર રહો.',
    recNormalItem7: '7. ડિજિટલ સેવ: આ PDF રિપોર્ટ તમારા હેલ્થ ફોલ્ડરમાં સુરક્ષિત રાખો.',
    recAbnormalItem1: '1. નિષ્ણાત સલાહ: 12-લીડ ECG ટેસ્ટ માટે નિષ્ણાત કાર્ડિયોલોજિસ્ટની મુલાકાત લો.',
    recAbnormalItem2: '2. લક્ષણ ટ્રેકિંગ: ચક્કર આવવા કે ઘભરામણ જેવા લક્ષણો નોંધો.',
    recAbnormalItem3: '3. કટોકટી ચેતવણી: છાતીમાં તીવ્ર દુખાવો થાય તો તાત્કાલિક મદદ લો.',
    recAbnormalItem4: '4. દૈનિક વાઇટલ્સ ચેક: સવાર-સાંજ હૃદય દર અને બ્લડ પ્રેશર નોંધો.',
    recAbnormalItem5: '5. દવા સમીક્ષા: તમારી દવાની યાદી તબીબને બતાવી સલાહ લો.',
    recAbnormalItem6: '6. શારીરિક શ્રમ પર નિયંત્રણ: ડોક્ટરની મંજૂરી સુધી ભારે કસરત ટાળો.',
    recAbnormalItem7: '7. રિપોર્ટ શેરિંગ: આ સ્ક્રીનીંગ રિપોર્ટ તમારા કાર્ડિયોલોજિસ્ટ સાથે શેર કરો.',
    disclaimerTitle: 'મહત્વપૂર્ણ તબીબી અસ્વીકરણ',
    disclaimerBody: 'આ રિપોર્ટ માત્ર સ્ક્રીનીંગ હેતુઓ માટે જ જનરેટ કરવામાં આવ્યો છે. તે ઔપચારિક તબીબી નિદાન નથી.',
  },
  mr: {
    reportTitle: 'कार्डिओसेन्स AI',
    subTitle: 'क्लिनिकल कार्डियाक वेव्हफॉर्म अहवाल',
    patientSection: '१. रुग्ण आणि रेकॉर्डिंग माहिती',
    patientName: 'रुग्णाचे नाव:',
    ageGender: 'वय / लिंग:',
    fileName: 'रेकॉर्डिंग फाइल:',
    fileType: 'सिग्नल प्रकार:',
    processedAt: 'अहवाल तारीख:',
    metricsSection: '२. हृदयगती आणि वेव्हफॉर्म परिणाम',
    qualityScore: 'सिग्नल गुणवत्ता स्कोर:',
    noiseLevel: 'नॉईज पातळी:',
    baselineStability: 'बेसलाइन स्थिरता:',
    heartRateAvg: 'सरासरी हृदयगती:',
    hrRange: 'किमान / कमाल हृदयगती:',
    hrVariability: 'हृदयगती परिवर्तनशीलता:',
    prInterval: 'अंदाजित PR कालावधी:',
    qrsDuration: 'अंदाजित QRS कालावधी:',
    qtcInterval: 'अंदाजित QTc कालावधी:',
    aiSection: '३. AI डीप लर्निंग वर्गीकरण निकाल',
    classificationLabel: 'AI प्राथमिक वर्गीकरण:',
    confidenceLabel: 'मॉडेल आत्मविश्वास स्कोर:',
    probabilityTitle: 'संभाव्यता वितरण:',
    graphSection: '४. वेव्हफॉर्म आलेख (ECG ग्रीड कागद)',
    explainableSection: '५. AI मॉडेल तुलना आणि XAI आलेख',
    focusSegment: 'लक्ष क्षेत्र कालावधी:',
    focusDescription: 'मॉडेल निरीक्षण:',
    riskSection: '६. वैद्यकीय धोका मूल्यमापन',
    riskLevel: 'धोका पातळी:',
    doctorSection: '७. डॉक्टर क्लिनिकल पडताळणी',
    reviewedBy: 'तपासणी करणारे डॉक्टर:',
    clinicalAssessment: 'क्लिनिकल मूल्यमापन:',
    clinicalNotes: 'डॉक्टर टीप:',
    recommendationsSection: '8. क्लिनिकल शिफारसी आणि कृती योजना (काय करावे)',
    recNormalItem1: '1. नियमित देखरेख: नियमित वार्षिक आरोग्य तपासणी सुरू ठेवा.',
    recNormalItem2: '2. निरोगी सवयी: संतुलित आहार, पुरेसे पाणी आणि नियमित व्यायाम करा.',
    recNormalItem3: '3. ॲरोबिक व्यायाम: दर आठवड्याला १५० मिनिटे मध्यम व्यायाम करा.',
    recNormalItem4: '4. हृदयगती ट्रॅकिंग: आठवड्यातून एकदा विश्रांतीच्या वेळेची हृदयगती नोंदवा.',
    recNormalItem5: '5. डॉक्टर सल्ला: पुढील तपासणीदरम्यान डॉक्टरांशी चर्चा करा.',
    recNormalItem6: '6. जीवनशैली सुधारणा: तंबाखूचे सेवन टाळा आणि कॅफिन मर्यादित करा.',
    recNormalItem7: '7. डिजिटल संचयन: हा PDF अहवाल सुरक्षित ठेवा.',
    recAbnormalItem1: '1. तज्ज्ञ सल्ला: १२-लीड ECG तपासणीसाठी कार्डियोलॉजिस्टचा सल्ला घ्या.',
    recAbnormalItem2: '2. लक्षणे ट्रॅकिंग: चक्कर येणे किंवा छातीत धडधडणे यावर लक्ष ठेवा.',
    recAbnormalItem3: '3. आणीबाणी इशारा: तीव्र छातीत दुखणे जाणवल्यास त्वरित वैद्यकीय मदत घ्या.',
    recAbnormalItem4: '4. दैनिक रक्तदाब तपासणी: सकाळी आणि संध्याकाळी हृदयगती व बीपी नोंदवा.',
    recAbnormalItem5: '5. औषध पुनरावलोकन: औषधांची यादी डॉक्टरांना दाखवून सल्ला घ्या.',
    recAbnormalItem6: '6. कष्टाच्या कामावर नियंत्रण: डॉक्टरांच्या सल्ल्याशिवाय जड व्यायाम करू नका.',
    recAbnormalItem7: '7. अहवाल शेअरिंग: हा अहवाल डॉक्टरांसोबत शेअर करा.',
    disclaimerTitle: 'महत्त्वाचे वैद्यकीय अस्वीकरण',
    disclaimerBody: 'हा अहवाल केवळ स्क्रीनिंगच्या उद्देशाने तयार केला आहे. हे औपचारिक वैद्यकीय निदान नाही.',
  },
  bn: {
    reportTitle: 'কার্ডিওসেন্স AI',
    subTitle: 'ক্লিনিকাল কার্ডিয়াক ওয়েভফর্ম স্ক্রিনিং রিপোর্ট',
    patientSection: '১. রোগী এবং রেকর্ডিং তথ্য',
    patientName: 'রোগীর নাম:',
    ageGender: 'বয়স / লিঙ্গ:',
    fileName: 'রেকর্ডিং ফাইল:',
    fileType: 'সংকেত প্রকার:',
    processedAt: 'রিপোর্টের তারিখ:',
    metricsSection: '২. হৃদস্পন্দন এবং ওয়েভফর্ম পরিমিতি',
    qualityScore: 'সংকেত গুণমান স্কোর:',
    noiseLevel: 'শব্দ মাত্রা:',
    baselineStability: 'বেসলাইন স্থায়িত্ব:',
    heartRateAvg: 'গড় হৃদস্পন্দন:',
    hrRange: 'সর্বনিম্ন / সর্বোচ্চ হৃদস্পন্দন:',
    hrVariability: 'হৃদস্পন্দন পরিবর্তনশীলতা:',
    prInterval: 'আনুমানিক PR সময়কাল:',
    qrsDuration: 'আনুমানিক QRS সময়কাল:',
    qtcInterval: 'আনুমানিক QTc সময়কাল:',
    aiSection: '৩. AI ডিপ লার্নিং শ্রেণীবিভাগ ফলাফল',
    classificationLabel: 'AI প্রাথমিক শ্রেণীবিভাগ:',
    confidenceLabel: 'মডেল আত্মবিশ্বাসের স্কোর:',
    probabilityTitle: 'শ্রেণী সম্ভাব্যতা বন্টন:',
    graphSection: '৪. ওয়েভফর্ম গ্রাফ (ECG গ্রিড পেপার)',
    explainableSection: '৫. AI মডেল তুলনা এবং XAI গ্রাফ',
    focusSegment: 'ফোকাস সময়সীমা:',
    focusDescription: 'মডেল পর্যবেক্ষণ:',
    riskSection: '৬. ক্লিনিকাল ঝুঁকি মূল্যায়ন',
    riskLevel: 'ঝুঁকির মাত্রা:',
    doctorSection: '৭. চিকিৎসক ক্লিনিকাল মূল্যায়ন',
    reviewedBy: 'পর্যালোচনা কারী চিকিৎসক:',
    clinicalAssessment: 'ক্লিনিকাল মূল্যায়ন:',
    clinicalNotes: 'চিকিৎসকের নোট:',
    recommendationsSection: '8. ক্লিনিকাল সুপারিশ এবং কার্য পরিকল্পনা (কী করণীয়)',
    recNormalItem1: '1. নিয়মিত পর্যবেক্ষণ: নিয়মিত বার্ষিক স্বাস্থ্য পরীক্ষা বজায় রাখুন।',
    recNormalItem2: '2. স্বাস্থ্যকর অভ্যাস: সুষম খাদ্য, পর্যাপ্ত জল এবং নিয়মিত ব্যায়াম বজায় রাখুন।',
    recNormalItem3: '3. অ্যারোবিক ব্যায়াম: প্রতি সপ্তাহে ১৫০ মিনিট মাঝারি ব্যায়াম করুন।',
    recNormalItem4: '4. হৃদস্পন্দন ট্র্যাকিং: সপ্তাহে একবার বিশ্রামের হৃদস্পন্দন লক্ষ্য করুন।',
    recNormalItem5: '5. ডাক্তার পরামর্শ: পরবর্তী চেকআপে স্বাস্থ্য নিয়ে আলোচনা করুন।',
    recNormalItem6: '6. তামাক এড়িয়ে চলা: তামাক ব্যবহার থেকে বিরত থাকুন।',
    recNormalItem7: '7. ডিজিটাল সংরক্ষণ: এই পিডিএফ রিপোর্টটি নিজের ফোল্ডারে রাখুন।',
    recAbnormalItem1: '1. বিশেষজ্ঞ পরামর্শ: ১২-লিড ECG পরীক্ষার জন্য কার্ডিওলজিস্টের পরামর্শ নিন।',
    recAbnormalItem2: '2. লক্ষণ পর্যবেক্ষণ: মাথা ঘোরা বা বুক ধড়ফড় লক্ষণগুলি খেয়াল রাখুন।',
    recAbnormalItem3: '3. জরুরি সতর্কবার্তা: তীব্র বুক ব্যথা হলে অবিলম্বে জরুরি চিকিৎসা সেবা নিন।',
    recAbnormalItem4: '4. দৈনিক রক্তচাপ পরিমাপ: প্রতিদিন সকাল ও সন্ধ্যায় প্রেশার পরীক্ষা করুন।',
    recAbnormalItem5: '5. ওষুধ পর্যালোচনা: বর্তমান ওষুধের তালিকা ডাক্তারকে দেখান।',
    recAbnormalItem6: '6. শারীরিক পরিশ্রম নিয়ন্ত্রণ: ডাক্তারের অনুমতি ছাড়া ভারী ব্যায়াম করবেন না।',
    recAbnormalItem7: '7. রিপোর্ট শেয়ারিং: এই রিপোর্টটি ডাক্তারের সাথে ভাগ করুন।',
    disclaimerTitle: 'গুরুত্বপূর্ণ চিকিৎসা সংক্রান্ত সতর্কবার্তা',
    disclaimerBody: 'এই রিপোর্টটি শুধুমাত্র স্ক্রিনিং এর উদ্দেশ্যে তৈরি করা হয়েছে। এটি কোন প্রাতিষ্ঠানিক চিকিৎসা নির্ণয় নয়।',
  },
  kn: {
    reportTitle: 'ಕಾರ್ಡಿಯೋಸೆನ್ಸ್ AI',
    subTitle: 'ಕ್ಲಿನಿಕಲ್ ಕಾರ್ಡಿಯಾಕ್ ಸಿಗ್ನಲ್ ಸ್ಕ್ರೀನಿಂಗ್ ವರದಿ',
    patientSection: '1. ರೋಗಿ ಮತ್ತು ರೆಕಾರ್ಡಿಂಗ್ ಮಾಹಿತಿ',
    patientName: 'ರೋಗಿಯ ಹೆಸರು:',
    ageGender: 'ವಯಸ್ಸು / ಲಿಂಗ:',
    fileName: 'ರೆಕಾರ್ಡಿಂಗ್ ಫೈಲ್:',
    fileType: 'ಸಿಗ್ನಲ್ ಪ್ರಕಾರ:',
    processedAt: 'ವರದಿ ದಿನಾಂಕ:',
    metricsSection: '2. ಹೃದಯ ಬಡಿತ ಮತ್ತು ಸಿಗ್ನಲ್ ನಿಯತಾಂಕಗಳು',
    qualityScore: 'ಸಿಗ್ನಲ್ ಗುಣಮಟ್ಟದ ಸ್ಕೋರ್:',
    noiseLevel: 'ಶಬ್ದದ ಮಟ್ಟ:',
    baselineStability: 'ಬೇಸ್‌ಲೈನ್ ಸ್ಥಿರತೆ:',
    heartRateAvg: 'ಸರಾಸರಿ ಹೃದಯ ಬಡಿತ:',
    hrRange: 'ಕನಿಷ್ಠ / ಗರಿಷ್ಠ ಹೃದಯ ಬಡಿತ:',
    hrVariability: 'ಹೃದಯ ಬಡಿತದ ವ್ಯತ್ಯಾಸ:',
    prInterval: 'ಅಂದಾಜು PR ಅವಧಿ:',
    qrsDuration: 'ಅಂದಾಜು QRS ಅವಧಿ:',
    qtcInterval: 'ಅಂದಾಜು QTc ಅವಧಿ:',
    aiSection: '3. AI ಡೀಪ್ ಲರ್ನಿಂಗ್ ವರ್ಗೀಕರಣ ಫಲಿತಾಂಶ',
    classificationLabel: 'AI ಪ್ರಾಥಮಿಕ ವರ್ಗೀಕರಣ:',
    confidenceLabel: 'ಮಾಡೆಲ್ ವಿಶ್ವಾಸಾರ್ಹತೆ ಸ್ಕೋರ್:',
    probabilityTitle: 'ಸಂಭಾವ್ಯತೆಯ ಹಂಚಿಕೆ ವಿವರಣೆ:',
    graphSection: '4. ಸಿಗ್ನಲ್ ಗ್ರಾಫ್ (ECG ಗ್ರಿಡ್ ಪೇಪರ್)',
    explainableSection: '5. AI ಮಾಡೆಲ್ ಹೋಲಿಕೆ ಮತ್ತು XAI ಗ್ರಾಫ್',
    focusSegment: 'ಗಮನ ಅವಧಿ ಸಮಯ:',
    focusDescription: 'ಮಾಡೆಲ್ ವೀಕ್ಷಣೆ:',
    riskSection: '6. ಕ್ಲಿನಿಕಲ್ ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ',
    riskLevel: 'ಅಪಾಯದ ಮಟ್ಟ:',
    doctorSection: '7. ವೈದ್ಯರ ಕ್ಲಿನಿಕಲ್ ಪರಿಶೀಲನೆ',
    reviewedBy: 'ಪರಿಶೀಲಿಸಿದ ವೈದ್ಯರು:',
    clinicalAssessment: 'ಕ್ಲಿನಿಕಲ್ ಮೌಲ್ಯಮಾಪನ:',
    clinicalNotes: 'ವೈದ್ಯರ ಟಿಪ್ಪಣಿಗಳು:',
    recommendationsSection: '8. ಕ್ಲಿನಿಕಲ್ ಕ್ರಿಯಾ ಯೋಜನೆ ಮತ್ತು ಶಿಫಾರಸುಗಳು (ಏನು ಮಾಡಬೇಕು)',
    recNormalItem1: '1. ನಿಯಮಿತ ತಪಾಸಣೆ: ನಿಯಮಿತ ವಾರ್ಷಿಕ ಹೃದಯ ಆರೋಗ್ಯ ತಪಾಸಣೆಯನ್ನು ಮುಂದುವರಿಸಿ.',
    recNormalItem2: '2. ಜೀವನಶೈಲಿ ನಿರ್ವಹಣೆ: ಸಮತೋಲಿತ ಆಹಾರ, ನಿಯಮಿತ ವ್ಯಾಯಾಮ ಮತ್ತು ಮಾನಸಿಕ ಶಾಂತಿಯನ್ನು ಕಾಯ್ದುಕೊಳ್ಳಿ.',
    recNormalItem3: '3. ಏರೋಬಿಕ್ ವ್ಯಾಯಾಮ: ವಾರಕ್ಕೆ 150 ನಿಮಿಷಗಳ ಸಾಧಾರಣ ವ್ಯಾಯಾಮ ಮಾಡಿ.',
    recNormalItem4: '4. ಹೃದಯ ಬಡಿತದ ಟ್ರ್ಯಾಕಿಂಗ್: ವಾರಕ್ಕೊಮ್ಮೆ ವಿಶ್ರಾಂತಿ ಸಮಯದ ಹೃದಯ ಬಡಿತವನ್ನು ನಮೂದಿಸಿ.',
    recNormalItem5: '5. ವೈದ್ಯರ ಸಲಹೆ: ಮುಂದಿನ ತಪಾಸಣೆಯಲ್ಲಿ ವೈದ್ಯರೊಂದಿಗೆ ಈ ಫಲಿತಾಂಶಗಳನ್ನು ಚರ್ಚಿಸಿ.',
    recNormalItem6: '6. ಧೂಮಪಾನ ನಿಷೇಧ: ತಂಬಾಕು ಸೇವನೆ ಮತ್ತು ಅಧಿಕ ಕೆಫೀನ್ ಸೇವನೆಯಿಂದ ದೂರವಿರಿ.',
    recNormalItem7: '7. ಡಿಜಿಟಲ್ ಫೈಲ್ ಸಂಗ್ರಹಣೆ: ಈ PDF ವರದಿಯನ್ನು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಫೋಲ್ಡರ್‌ನಲ್ಲಿ ಉಳಿಸಿ.',
    recAbnormalItem1: '1. ತಜ್ಞರ ಸಲಹೆ: 12-ಲೀಡ್ ECG ಪರೀಕ್ಷೆಗಾಗಿ ಅರ್ಹ ಹೃದ್ರೋಗ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    recAbnormalItem2: '2. ರೋಗಲಕ್ಷಣಗಳ ಟ್ರ್ಯಾಕಿಂಗ್: ತಲೆತಿರುಗುವಿಕೆ, ಎದೆಬಡಿತ ಅಥವಾ ಉಸಿರಾಟದ ತೊಂದರೆಯನ್ನು ಗಮನಿಸಿ.',
    recAbnormalItem3: '3. ತುರ್ತು ಎಚ್ಚರಿಕೆ: ತೀವ್ರ ಎದೆನೋವು ಉಂಟಾದರೆ ತಕ್ಷಣವೇ ತುರ್ತು ವೈದ್ಯಕೀಯ ನೆರವು ಪಡೆಯಿರಿ.',
    recAbnormalItem4: '4. ದೈನಂದಿನ ರಕ್ತದೊತ್ತಡ ತಪಾಸಣೆ: ಬೆಳಿಗ್ಗೆ ಮತ್ತು ಸಂಜೆ ಹೃದಯ ಬಡಿತ ಮತ್ತು ರಕ್ತದೊತ್ತಡವನ್ನು ನಮೂದಿಸಿ.',
    recAbnormalItem5: '5. ಔಷಧ ಪರಿಶೀಲನೆ: ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಔಷಧಿಗಳ ಪಟ್ಟಿಯನ್ನು ವೈದ್ಯರಿಗೆ ತೋರಿಸಿ ಸಲಹೆ ಪಡೆಯಿರಿ.',
    recAbnormalItem6: '6. ದೈಹಿಕ ಶ್ರಮ ನಿಯಂತ್ರಣ: ವೈದ್ಯರು ಅನುಮತಿಸುವವರೆಗೆ ಕಠಿಣ ವ್ಯಾಯಾಮ ಮಾಡಬೇಡಿ.',
    recAbnormalItem7: '7. ವರದಿ ಹಂಚಿಕೆ: ಈ ಸ್ಕ್ರೀನಿಂಗ್ ವರದಿಯನ್ನು ನಿಮ್ಮ ವೈದ್ಯರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ.',
    disclaimerTitle: 'ಪ್ರಮುಖ ವೈದ್ಯಕೀಯ ಹಕ್ಕುತ್ಯಾಗ',
    disclaimerBody: 'ಈ ವರದಿಯನ್ನು ಕಾರ್ಡಿಯೋಸೆನ್ಸ್ AI ಸ್ಕ್ರೀನಿಂಗ್ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ ಸಿದ್ಧಪಡಿಸಲಾಗಿದೆ. ಇದು ಅಧಿಕೃತ ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯವಲ್ಲ.',
  },
}

// Helper to render Cardiosense AI Emblem Logo as Data URL for PDF Header
export function renderLogoToCanvas(): string {
  if (typeof document === 'undefined') return ''
  try {
    const canvas = document.createElement('canvas')
    canvas.width = 240
    canvas.height = 240
    const ctx = canvas.getContext('2d')
    if (!ctx) return ''

    // Outer Circle Shield
    ctx.beginPath()
    ctx.arc(120, 120, 108, 0, 2 * Math.PI)
    ctx.fillStyle = '#F0FDFA'
    ctx.fill()
    ctx.strokeStyle = '#CCFBF1'
    ctx.lineWidth = 10
    ctx.stroke()

    // Heart Outline
    ctx.beginPath()
    ctx.moveTo(120, 192)
    ctx.bezierCurveTo(48, 142, 28, 92, 58, 60)
    ctx.bezierCurveTo(78, 32, 108, 48, 120, 68)
    ctx.bezierCurveTo(132, 48, 162, 32, 182, 60)
    ctx.bezierCurveTo(212, 92, 192, 142, 120, 192)
    ctx.strokeStyle = '#0D9488'
    ctx.lineWidth = 12
    ctx.stroke()

    // ECG Wave Line
    ctx.beginPath()
    ctx.moveTo(22, 120)
    ctx.lineTo(72, 120)
    ctx.lineTo(84, 102)
    ctx.lineTo(96, 150)
    ctx.lineTo(112, 42)
    ctx.lineTo(132, 182)
    ctx.lineTo(146, 110)
    ctx.lineTo(158, 125)
    ctx.lineTo(218, 120)
    ctx.strokeStyle = '#E11D48'
    ctx.lineWidth = 13
    ctx.stroke()

    // Sensing Dot
    ctx.beginPath()
    ctx.arc(112, 42, 8, 0, 2 * Math.PI)
    ctx.fillStyle = '#E11D48'
    ctx.fill()

    return canvas.toDataURL('image/png')
  } catch {
    return ''
  }
}

// Function to render standard ECG Millimeter Grid Graph to Image PNG
export function renderECGGraphCanvas(rawSignal: number[], focusArea?: any): string {
  if (typeof document === 'undefined') return ''
  try {
    const canvas = document.createElement('canvas')
    canvas.width = 1100
    canvas.height = 280
    const ctx = canvas.getContext('2d')
    if (!ctx) return ''

    // 1. Draw Background ECG Pink Millimeter Grid Paper
    ctx.fillStyle = '#FFFDFD'
    ctx.fillRect(0, 0, canvas.width, canvas.height)

    // Minor Grid Lines (1mm equivalent)
    ctx.strokeStyle = '#FCE7F3'
    ctx.lineWidth = 0.5
    for (let x = 0; x < canvas.width; x += 8) {
      ctx.beginPath()
      ctx.moveTo(x, 0)
      ctx.lineTo(x, canvas.height)
      ctx.stroke()
    }
    for (let y = 0; y < canvas.height; y += 8) {
      ctx.beginPath()
      ctx.moveTo(0, y)
      ctx.lineTo(canvas.width, y)
      ctx.stroke()
    }

    // Major Grid Lines (5mm equivalent)
    ctx.strokeStyle = '#F87171'
    ctx.lineWidth = 1.2
    for (let x = 0; x < canvas.width; x += 40) {
      ctx.beginPath()
      ctx.moveTo(x, 0)
      ctx.lineTo(x, canvas.height)
      ctx.stroke()
    }
    for (let y = 0; y < canvas.height; y += 40) {
      ctx.beginPath()
      ctx.moveTo(0, y)
      ctx.lineTo(canvas.width, y)
      ctx.stroke()
    }

    // 2. Draw AI Attention Focus Area Highlight
    if (focusArea) {
      const totalDuration = 15 // sec
      const startRatio = focusArea.startTime / totalDuration
      const endRatio = focusArea.endTime / totalDuration
      const startX = startRatio * canvas.width
      const widthX = (endRatio - startRatio) * canvas.width

      ctx.fillStyle = 'rgba(245, 158, 11, 0.28)'
      ctx.fillRect(startX, 0, widthX, canvas.height)

      ctx.fillStyle = '#D97706'
      ctx.font = 'bold 12px sans-serif'
      ctx.fillText('AI Attention Region (' + focusArea.startTime + 's - ' + focusArea.endTime + 's)', startX + 6, 20)
    }

    // 3. Plot Signal Waveform
    if (rawSignal && rawSignal.length > 0) {
      const points = rawSignal.length
      const minVal = Math.min(...rawSignal) - 0.2
      const maxVal = Math.max(...rawSignal) + 0.2
      const range = maxVal - minVal || 1

      ctx.beginPath()
      ctx.strokeStyle = '#0F2942' // Clinical Deep Navy Line
      ctx.lineWidth = 2.2

      for (let i = 0; i < points; i++) {
        const x = (i / (points - 1)) * canvas.width
        const normY = (rawSignal[i] - minVal) / range
        const y = canvas.height - normY * (canvas.height - 40) - 20
        if (i === 0) ctx.moveTo(x, y)
        else ctx.lineTo(x, y)
      }
      ctx.stroke()
    }

    // 4. Calibration & Scale Legend
    ctx.fillStyle = '#475569'
    ctx.font = 'bold 11px sans-serif'
    ctx.fillText('ECG Calibration: 25 mm/s | 10 mm/mV | Sampling Rate: 100 Hz', 12, canvas.height - 10)

    return canvas.toDataURL('image/png')
  } catch {
    return ''
  }
}

// Function to render AI Saliency Heatmap & Normal Reference Overlay Canvas Graph
export function renderComparisonGraphCanvas(rawSignal: number[], focusArea?: any): string {
  if (typeof document === 'undefined') return ''
  try {
    const canvas = document.createElement('canvas')
    canvas.width = 1100
    canvas.height = 280
    const ctx = canvas.getContext('2d')
    if (!ctx) return ''

    // 1. Background Grid
    ctx.fillStyle = '#F8FAFC'
    ctx.fillRect(0, 0, canvas.width, canvas.height)

    ctx.strokeStyle = '#E2E8F0'
    ctx.lineWidth = 0.8
    for (let x = 0; x < canvas.width; x += 40) {
      ctx.beginPath()
      ctx.moveTo(x, 0)
      ctx.lineTo(x, canvas.height)
      ctx.stroke()
    }
    for (let y = 0; y < canvas.height; y += 40) {
      ctx.beginPath()
      ctx.moveTo(0, y)
      ctx.lineTo(canvas.width, y)
      ctx.stroke()
    }

    // 2. Synthetic Normal Healthy Baseline Trace (Teal dashed reference)
    if (rawSignal && rawSignal.length > 0) {
      const points = rawSignal.length
      ctx.beginPath()
      ctx.setLineDash([6, 4])
      ctx.strokeStyle = '#0D9488' // Medical Teal
      ctx.lineWidth = 1.8

      for (let i = 0; i < points; i++) {
        const x = (i / (points - 1)) * canvas.width
        const t = (i / points) * 10 * Math.PI * 2
        const normY = Math.sin(t) * 0.25 + Math.sin(t * 4) * 0.12 + 0.5
        const y = canvas.height - normY * (canvas.height - 60) - 30
        if (i === 0) ctx.moveTo(x, y)
        else ctx.lineTo(x, y)
      }
      ctx.stroke()
      ctx.setLineDash([])
    }

    // 3. AI Focus Heatmap Highlight
    if (focusArea) {
      const totalDuration = 15
      const startRatio = focusArea.startTime / totalDuration
      const endRatio = focusArea.endTime / totalDuration
      const startX = startRatio * canvas.width
      const widthX = (endRatio - startRatio) * canvas.width

      ctx.fillStyle = 'rgba(239, 68, 68, 0.22)'
      ctx.fillRect(startX, 0, widthX, canvas.height)
      ctx.fillStyle = '#DC2626'
      ctx.font = 'bold 12px sans-serif'
      ctx.fillText('1D-CNN Model Gradient Saliency Focus Window (' + focusArea.startTime + 's - ' + focusArea.endTime + 's)', startX + 6, 22)
    }

    // 4. Patient Waveform Trace (Navy solid line)
    if (rawSignal && rawSignal.length > 0) {
      const points = rawSignal.length
      const minVal = Math.min(...rawSignal) - 0.2
      const maxVal = Math.max(...rawSignal) + 0.2
      const range = maxVal - minVal || 1

      ctx.beginPath()
      ctx.strokeStyle = '#1E1B4B' // Deep Navy Line
      ctx.lineWidth = 2.4

      for (let i = 0; i < points; i++) {
        const x = (i / (points - 1)) * canvas.width
        const normY = (rawSignal[i] - minVal) / range
        const y = canvas.height - normY * (canvas.height - 60) - 30
        if (i === 0) ctx.moveTo(x, y)
        else ctx.lineTo(x, y)
      }
      ctx.stroke()
    }

    // Legend
    ctx.fillStyle = '#0D9488'
    ctx.font = 'bold 11px sans-serif'
    ctx.fillText('--- Normal Healthy Baseline Reference', 15, canvas.height - 12)
    ctx.fillStyle = '#1E1B4B'
    ctx.fillText('─── Patient Waveform Recording', 260, canvas.height - 12)
    ctx.fillStyle = '#DC2626'
    ctx.fillText('█ 1D-CNN AI Attention Region', 470, canvas.height - 12)

    return canvas.toDataURL('image/png')
  } catch {
    return ''
  }
}

export function generateAnalysisPDF(
  analysis: Analysis,
  user?: User | null,
  language: ReportLanguage = 'en'
): void {
  const t = PDF_TRANSLATIONS[language] || PDF_TRANSLATIONS.en

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let y = 0

  // Helper to draw Header Banner on any page
  const drawPageHeader = () => {
    // Header Banner Box
    doc.setFillColor(15, 41, 66) // #0F2942 Clinical Deep Navy
    doc.rect(0, 0, pageWidth, 28, 'F')

    // Teal Accent Strip
    doc.setFillColor(13, 148, 136) // #0D9488 Medical Teal
    doc.rect(0, 28, pageWidth, 2, 'F')

    // Render Emblem Logo in Header
    const logoDataUrl = renderLogoToCanvas()
    if (logoDataUrl) {
      doc.addImage(logoDataUrl, 'PNG', 12, 4, 20, 20)
    }

    // Header Title & Subtitle
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    doc.text(t.reportTitle, 36, 14)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(204, 251, 241) // Teal light text
    doc.text(t.subTitle, 36, 21)
  }

  // Draw Page 1 Header
  drawPageHeader()
  y = 36

  // Helper to check page bounds and auto-page break
  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 28) {
      doc.addPage()
      drawPageHeader()
      y = 36
    }
  }

  // --- SECTION 1: PATIENT & RECORDING METADATA ---
  checkPageBreak(30)
  doc.setDrawColor(226, 232, 240)
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(14, y, pageWidth - 28, 28, 2, 2, 'FD')

  doc.setTextColor(15, 23, 42)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text(t.patientSection, 18, y + 7)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(51, 65, 85)

  const patientName = analysis.patientName || (user?.role === 'patient' ? user.name : 'Rajesh Sharma')
  const patientAge = analysis.patientAge || (user?.role === 'patient' ? user.age : 45)
  const patientGender = analysis.patientGender || (user?.role === 'patient' ? user.gender : 'Male')
  const ageGender = `${patientAge} yrs / ${patientGender}`
  const formattedDate = new Date(analysis.uploadedAt).toLocaleString()

  doc.text(`${t.patientName} ${patientName}`, 18, y + 15)
  doc.text(`${t.ageGender} ${ageGender}`, 18, y + 22)

  doc.text(`${t.fileName} ${analysis.fileName}`, 105, y + 15)
  doc.text(`${t.processedAt} ${formattedDate}`, 105, y + 22)

  y += 34

  // --- SECTION 2: QUANTITATIVE CARDIAC VITALS & ELECTROPHYSIOLOGICAL METRICS ---
  checkPageBreak(42)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 41, 66)
  doc.text(t.metricsSection, 14, y)
  y += 4

  doc.setLineWidth(0.3)
  doc.setDrawColor(203, 213, 225)
  doc.line(14, y, pageWidth - 14, y)
  y += 6

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(51, 65, 85)

  // Point-wise Vitals Metrics Table
  doc.text(`${t.qualityScore} ${analysis.signalQuality.score}% (${analysis.signalQuality.status})`, 18, y)
  doc.text(`${t.heartRateAvg} ${analysis.heartRate.average} BPM`, 110, y)
  y += 5

  doc.text(`${t.noiseLevel} ${analysis.signalQuality.factors.noise.toUpperCase()}`, 18, y)
  doc.text(`${t.hrRange} ${analysis.heartRate.min} - ${analysis.heartRate.max} BPM`, 110, y)
  y += 5

  doc.text(`${t.baselineStability} ${analysis.signalQuality.factors.baseline.toUpperCase()}`, 18, y)
  doc.text(`${t.hrVariability} ${analysis.heartRate.variability.toUpperCase()}`, 110, y)
  y += 5

  // Electrophysiological Interval Estimates
  doc.text(`${t.prInterval} ~160 ms (Normal: 120-200 ms)`, 18, y)
  doc.text(`${t.qrsDuration} ~92 ms (Normal: <120 ms)`, 110, y)
  y += 5

  doc.text(`${t.qtcInterval} ~410 ms (Normal: <440 ms)`, 18, y)
  y += 10

  // --- SECTION 3: DEEP LEARNING CLASSIFICATION & AI CONFIDENCE ---
  checkPageBreak(48)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 41, 66)
  doc.text(t.aiSection, 14, y)
  y += 4
  doc.line(14, y, pageWidth - 14, y)
  y += 6

  const isNormal = analysis.aiPrediction.class === 'Normal'
  doc.setFillColor(isNormal ? 240 : 254, isNormal ? 253 : 243, isNormal ? 250 : 199)
  doc.setDrawColor(isNormal ? 13 : 217, isNormal ? 148 : 119, isNormal ? 136 : 6)
  doc.roundedRect(14, y, pageWidth - 28, 18, 2, 2, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(isNormal ? 15 : 180, isNormal ? 118 : 83, isNormal ? 110 : 9)
  doc.text(`${t.classificationLabel} ${analysis.aiPrediction.class.toUpperCase()}`, 18, y + 8)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(51, 65, 85)
  doc.text(`${t.confidenceLabel} ${(analysis.aiPrediction.confidence * 100).toFixed(1)}%`, 18, y + 14)

  y += 24

  // Class Probability Distribution Point-Wise Table
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(15, 23, 42)
  doc.text(t.probabilityTitle, 14, y)
  y += 5

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  Object.entries(analysis.aiPrediction.classDistribution).forEach(([cls, prob]) => {
    const pct = (prob * 100).toFixed(1) + '%'
    doc.text(`• ${cls}:`, 18, y)
    doc.text(pct, 75, y)
    y += 4.5
  })

  y += 6

  // --- SECTION 4: DIAGNOSTIC SIGNAL WAVEFORM GRAPH (ECG GRID PAPER) ---
  // Ensure Section 4 ALWAYS starts on a fresh page if remaining space is less than 65mm
  if (y > 170) {
    doc.addPage()
    drawPageHeader()
    y = 36
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 41, 66)
  doc.text(t.graphSection, 14, y)
  y += 4
  doc.line(14, y, pageWidth - 14, y)
  y += 5

  // Render Canvas to Data URL and add to PDF
  const graphImgData = renderECGGraphCanvas(analysis.rawSignal, analysis.focusArea)
  if (graphImgData) {
    const graphWidth = pageWidth - 28
    const graphHeight = 42
    doc.addImage(graphImgData, 'PNG', 14, y, graphWidth, graphHeight)
    y += graphHeight + 8
  }

  // --- SECTION 5: AI MODEL SALIENCY & NORMAL BASELINE COMPARISON GRAPH ---
  if (y > 170) {
    doc.addPage()
    drawPageHeader()
    y = 36
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 41, 66)
  doc.text(t.explainableSection, 14, y)
  y += 4
  doc.line(14, y, pageWidth - 14, y)
  y += 5

  const comparisonImgData = renderComparisonGraphCanvas(analysis.rawSignal, analysis.focusArea)
  if (comparisonImgData) {
    const graphWidth = pageWidth - 28
    const graphHeight = 42
    doc.addImage(comparisonImgData, 'PNG', 14, y, graphWidth, graphHeight)
    y += graphHeight + 8
  }

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(51, 65, 85)
  doc.text(`${t.focusSegment} ${analysis.focusArea.startTime}s to ${analysis.focusArea.endTime}s`, 18, y)
  y += 5
  doc.text(`${t.focusDescription} ${analysis.focusArea.description}`, 18, y)
  y += 10

  // --- SECTION 6: RISK STRATIFICATION & TRIAGE GRADE ---
  checkPageBreak(25)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 41, 66)
  doc.text(t.riskSection, 14, y)
  y += 4
  doc.line(14, y, pageWidth - 14, y)
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)
  const riskGrade = isNormal ? 'LOW RISK (Grade I)' : 'MODERATE / ELEVATED RISK (Grade II)'
  const riskColor = isNormal ? [15, 118, 110] : [180, 83, 9]
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2])
  doc.text(`${t.riskLevel} ${riskGrade}`, 18, y)
  y += 10

  // --- SECTION 7: DOCTOR REVIEW / SIGN-OFF BLOCK IF AVAILABLE ---
  if (analysis.review) {
    checkPageBreak(25)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(15, 41, 66)
    doc.text(t.doctorSection, 14, y)
    y += 4
    doc.line(14, y, pageWidth - 14, y)
    y += 6

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(51, 65, 85)
    doc.text(`${t.reviewedBy} ${analysis.review.doctorName}`, 18, y)
    y += 4.5
    doc.text(`${t.clinicalAssessment} ${analysis.review.assessment}`, 18, y)
    y += 4.5
    doc.text(`${t.clinicalNotes} ${analysis.review.notes || 'None provided.'}`, 18, y)
    y += 10
  }

  // --- SECTION 8: 7-POINT CLINICAL RECOMMENDATIONS & ACTION PLAN ---
  checkPageBreak(50)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 41, 66)
  doc.text(t.recommendationsSection, 14, y)
  y += 4
  doc.line(14, y, pageWidth - 14, y)
  y += 6

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(51, 65, 85)

  if (isNormal) {
    doc.text(t.recNormalItem1, 18, y); y += 4.5
    doc.text(t.recNormalItem2, 18, y); y += 4.5
    doc.text(t.recNormalItem3, 18, y); y += 4.5
    doc.text(t.recNormalItem4, 18, y); y += 4.5
    doc.text(t.recNormalItem5, 18, y); y += 4.5
    doc.text(t.recNormalItem6, 18, y); y += 4.5
    doc.text(t.recNormalItem7, 18, y); y += 8
  } else {
    doc.text(t.recAbnormalItem1, 18, y); y += 4.5
    doc.text(t.recAbnormalItem2, 18, y); y += 4.5
    doc.text(t.recAbnormalItem3, 18, y); y += 4.5
    doc.text(t.recAbnormalItem4, 18, y); y += 4.5
    doc.text(t.recAbnormalItem5, 18, y); y += 4.5
    doc.text(t.recAbnormalItem6, 18, y); y += 4.5
    doc.text(t.recAbnormalItem7, 18, y); y += 8
  }

  // --- FOOTER DISCLAIMER BOX ---
  checkPageBreak(30)
  doc.setDrawColor(225, 29, 72)
  doc.setFillColor(254, 242, 242)
  doc.roundedRect(14, y, pageWidth - 28, 22, 2, 2, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(159, 18, 57)
  doc.text(t.disclaimerTitle, 18, y + 6)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(136, 19, 55)
  const lines = doc.splitTextToSize(t.disclaimerBody, pageWidth - 36)
  doc.text(lines, 18, y + 11)

  // Save PDF
  const filename = `Cardiosense_AI_Clinical_Report_${analysis.id}_${language.toUpperCase()}.pdf`
  doc.save(filename)
}
